// @generated by cargo xtask generate — do not edit

use crate::shared::{as_slice, int_param, to_py_err};
use numpy::{IntoPyArray, PyArray1, PyReadonlyArray1};
use pyo3::prelude::*;
use pyo3::types::PyDict;
use trendlib::TlError;
use trendlib::core::kernel::{BarStream, Kernel};
use trendlib::core::traits::Stream;

#[pyfunction]
#[pyo3(name = "ad", signature = (high, low, close, volume))]
pub fn ad<'py>(
    py: Python<'py>,
    high: PyReadonlyArray1<'py, f64>,
    low: PyReadonlyArray1<'py, f64>,
    close: PyReadonlyArray1<'py, f64>,
    volume: PyReadonlyArray1<'py, f64>,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let high = as_slice(&high, "high")?;
    let low = as_slice(&low, "low")?;
    let close = as_slice(&close, "close")?;
    let volume = as_slice(&volume, "volume")?;
    let params = trendlib::indicators::ad::Params;
    let out = py
        .detach(|| {
            <trendlib::indicators::ad::Ad as Kernel<4, 1>>::batch(
                [high, low, close, volume],
                &params,
            )
        })
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "AdStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyAdStream {
    inner: BarStream<trendlib::indicators::ad::Ad, 4, 1>,
}

#[pymethods]
impl PyAdStream {
    #[staticmethod]
    #[pyo3(signature = (high, low, close, volume))]
    fn open<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        volume: PyReadonlyArray1<'py, f64>,
    ) -> PyResult<Self> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let volume = as_slice(&volume, "volume")?;
        let params = trendlib::indicators::ad::Params;
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::ad::Ad, 4, 1> as Stream>::open(
                    [high, low, close, volume],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (high, low, close, volume))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        volume: PyReadonlyArray1<'py, f64>,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let volume = as_slice(&volume, "volume")?;
        let params = trendlib::indicators::ad::Params;
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::ad::Ad as Kernel<4, 1>>::open_and_fill(
                    [high, low, close, volume],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (high, low, close, volume))]
    fn update(
        &mut self,
        py: Python<'_>,
        high: f64,
        low: f64,
        close: f64,
        volume: f64,
    ) -> PyResult<f64> {
        let row = self
            .inner
            .update([high, low, close, volume])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (high, low, close, volume))]
    fn peek(&self, py: Python<'_>, high: f64, low: f64, close: f64, volume: f64) -> PyResult<f64> {
        let row = self
            .inner
            .peek([high, low, close, volume])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "ad"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream ad bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "atr", signature = (high, low, close, *, period))]
pub fn atr<'py>(
    py: Python<'py>,
    high: PyReadonlyArray1<'py, f64>,
    low: PyReadonlyArray1<'py, f64>,
    close: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let high = as_slice(&high, "high")?;
    let low = as_slice(&low, "low")?;
    let close = as_slice(&close, "close")?;
    let period = int_param("atr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::atr::Params { period };
    let out = py
        .detach(|| {
            <trendlib::indicators::atr::Atr as Kernel<3, 1>>::batch([high, low, close], &params)
        })
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "AtrStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyAtrStream {
    inner: BarStream<trendlib::indicators::atr::Atr, 3, 1>,
}

#[pymethods]
impl PyAtrStream {
    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("atr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::atr::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::atr::Atr, 3, 1> as Stream>::open(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("atr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::atr::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::atr::Atr as Kernel<3, 1>>::open_and_fill(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (high, low, close))]
    fn update(&mut self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .update([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (high, low, close))]
    fn peek(&self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .peek([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "atr"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream atr bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "cci", signature = (high, low, close, *, period))]
pub fn cci<'py>(
    py: Python<'py>,
    high: PyReadonlyArray1<'py, f64>,
    low: PyReadonlyArray1<'py, f64>,
    close: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let high = as_slice(&high, "high")?;
    let low = as_slice(&low, "low")?;
    let close = as_slice(&close, "close")?;
    let period = int_param("cci", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::cci::Params { period };
    let out = py
        .detach(|| {
            <trendlib::indicators::cci::Cci as Kernel<3, 1>>::batch([high, low, close], &params)
        })
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "CciStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyCciStream {
    inner: BarStream<trendlib::indicators::cci::Cci, 3, 1>,
}

#[pymethods]
impl PyCciStream {
    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("cci", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::cci::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::cci::Cci, 3, 1> as Stream>::open(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("cci", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::cci::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::cci::Cci as Kernel<3, 1>>::open_and_fill(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (high, low, close))]
    fn update(&mut self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .update([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (high, low, close))]
    fn peek(&self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .peek([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "cci"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream cci bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "dema", signature = (source, *, period))]
pub fn dema<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let source = as_slice(&source, "source")?;
    let period = int_param("dema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::dema::Params { period };
    let out = py
        .detach(|| <trendlib::indicators::dema::Dema as Kernel<1, 1>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "DemaStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyDemaStream {
    inner: BarStream<trendlib::indicators::dema::Dema, 1, 1>,
}

#[pymethods]
impl PyDemaStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("dema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::dema::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::dema::Dema, 1, 1> as Stream>::open(
                    [source],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("dema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::dema::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::dema::Dema as Kernel<1, 1>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "dema"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream dema bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "ema", signature = (source, *, period))]
pub fn ema<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let source = as_slice(&source, "source")?;
    let period = int_param("ema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::ema::Params { period };
    let out = py
        .detach(|| <trendlib::indicators::ema::Ema as Kernel<1, 1>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "EmaStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyEmaStream {
    inner: BarStream<trendlib::indicators::ema::Ema, 1, 1>,
}

#[pymethods]
impl PyEmaStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("ema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::ema::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::ema::Ema, 1, 1> as Stream>::open([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("ema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::ema::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::ema::Ema as Kernel<1, 1>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "ema"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream ema bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

type MacdOutputs<'py> = (
    Bound<'py, PyArray1<f64>>,
    Bound<'py, PyArray1<f64>>,
    Bound<'py, PyArray1<f64>>,
);

#[pyfunction]
#[pyo3(name = "macd", signature = (source, *, fast_period, slow_period, signal_period))]
pub fn macd<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    fast_period: i64,
    slow_period: i64,
    signal_period: i64,
) -> PyResult<MacdOutputs<'py>> {
    let source = as_slice(&source, "source")?;
    let fast_period =
        int_param("macd", "fast_period", fast_period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
    let slow_period =
        int_param("macd", "slow_period", slow_period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
    let signal_period = int_param("macd", "signal_period", signal_period, 1, 100000)
        .map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::macd::Params {
        fast_period,
        slow_period,
        signal_period,
    };
    let out = py
        .detach(|| <trendlib::indicators::macd::Macd as Kernel<1, 3>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok((
        std::mem::take(&mut out[0]).into_pyarray(py),
        std::mem::take(&mut out[1]).into_pyarray(py),
        std::mem::take(&mut out[2]).into_pyarray(py),
    ))
}

#[pyclass(module = "trendlib._core", name = "MacdStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyMacdStream {
    inner: BarStream<trendlib::indicators::macd::Macd, 1, 3>,
}

#[pymethods]
impl PyMacdStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, fast_period, slow_period, signal_period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        fast_period: i64,
        slow_period: i64,
        signal_period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let fast_period = int_param("macd", "fast_period", fast_period, 2, 100000)
            .map_err(|e| to_py_err(py, &e))?;
        let slow_period = int_param("macd", "slow_period", slow_period, 2, 100000)
            .map_err(|e| to_py_err(py, &e))?;
        let signal_period = int_param("macd", "signal_period", signal_period, 1, 100000)
            .map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::macd::Params {
            fast_period,
            slow_period,
            signal_period,
        };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::macd::Macd, 1, 3> as Stream>::open(
                    [source],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, fast_period, slow_period, signal_period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        fast_period: i64,
        slow_period: i64,
        signal_period: i64,
    ) -> PyResult<(Self, MacdOutputs<'py>)> {
        let source = as_slice(&source, "source")?;
        let fast_period = int_param("macd", "fast_period", fast_period, 2, 100000)
            .map_err(|e| to_py_err(py, &e))?;
        let slow_period = int_param("macd", "slow_period", slow_period, 2, 100000)
            .map_err(|e| to_py_err(py, &e))?;
        let signal_period = int_param("macd", "signal_period", signal_period, 1, 100000)
            .map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::macd::Params {
            fast_period,
            slow_period,
            signal_period,
        };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::macd::Macd as Kernel<1, 3>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            (
                std::mem::take(&mut out[0]).into_pyarray(py),
                std::mem::take(&mut out[1]).into_pyarray(py),
                std::mem::take(&mut out[2]).into_pyarray(py),
            )
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<(f64, f64, f64)> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok((row[0], row[1], row[2]))
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<(f64, f64, f64)> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok((row[0], row[1], row[2]))
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<(f64, f64, f64)> {
        self.inner.value().map(|row| (row[0], row[1], row[2]))
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "macd"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream macd bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "natr", signature = (high, low, close, *, period))]
pub fn natr<'py>(
    py: Python<'py>,
    high: PyReadonlyArray1<'py, f64>,
    low: PyReadonlyArray1<'py, f64>,
    close: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let high = as_slice(&high, "high")?;
    let low = as_slice(&low, "low")?;
    let close = as_slice(&close, "close")?;
    let period = int_param("natr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::natr::Params { period };
    let out = py
        .detach(|| {
            <trendlib::indicators::natr::Natr as Kernel<3, 1>>::batch([high, low, close], &params)
        })
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "NatrStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyNatrStream {
    inner: BarStream<trendlib::indicators::natr::Natr, 3, 1>,
}

#[pymethods]
impl PyNatrStream {
    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("natr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::natr::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::natr::Natr, 3, 1> as Stream>::open(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("natr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::natr::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::natr::Natr as Kernel<3, 1>>::open_and_fill(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (high, low, close))]
    fn update(&mut self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .update([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (high, low, close))]
    fn peek(&self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .peek([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "natr"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream natr bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "obv", signature = (close, volume))]
pub fn obv<'py>(
    py: Python<'py>,
    close: PyReadonlyArray1<'py, f64>,
    volume: PyReadonlyArray1<'py, f64>,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let close = as_slice(&close, "close")?;
    let volume = as_slice(&volume, "volume")?;
    let params = trendlib::indicators::obv::Params;
    let out = py
        .detach(|| {
            <trendlib::indicators::obv::Obv as Kernel<2, 1>>::batch([close, volume], &params)
        })
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "ObvStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyObvStream {
    inner: BarStream<trendlib::indicators::obv::Obv, 2, 1>,
}

#[pymethods]
impl PyObvStream {
    #[staticmethod]
    #[pyo3(signature = (close, volume))]
    fn open<'py>(
        py: Python<'py>,
        close: PyReadonlyArray1<'py, f64>,
        volume: PyReadonlyArray1<'py, f64>,
    ) -> PyResult<Self> {
        let close = as_slice(&close, "close")?;
        let volume = as_slice(&volume, "volume")?;
        let params = trendlib::indicators::obv::Params;
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::obv::Obv, 2, 1> as Stream>::open(
                    [close, volume],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (close, volume))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        close: PyReadonlyArray1<'py, f64>,
        volume: PyReadonlyArray1<'py, f64>,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let close = as_slice(&close, "close")?;
        let volume = as_slice(&volume, "volume")?;
        let params = trendlib::indicators::obv::Params;
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::obv::Obv as Kernel<2, 1>>::open_and_fill(
                    [close, volume],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (close, volume))]
    fn update(&mut self, py: Python<'_>, close: f64, volume: f64) -> PyResult<f64> {
        let row = self
            .inner
            .update([close, volume])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (close, volume))]
    fn peek(&self, py: Python<'_>, close: f64, volume: f64) -> PyResult<f64> {
        let row = self
            .inner
            .peek([close, volume])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "obv"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream obv bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "roc", signature = (source, *, period))]
pub fn roc<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let source = as_slice(&source, "source")?;
    let period = int_param("roc", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::roc::Params { period };
    let out = py
        .detach(|| <trendlib::indicators::roc::Roc as Kernel<1, 1>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "RocStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyRocStream {
    inner: BarStream<trendlib::indicators::roc::Roc, 1, 1>,
}

#[pymethods]
impl PyRocStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("roc", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::roc::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::roc::Roc, 1, 1> as Stream>::open([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("roc", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::roc::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::roc::Roc as Kernel<1, 1>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "roc"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream roc bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "rsi", signature = (source, *, period))]
pub fn rsi<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let source = as_slice(&source, "source")?;
    let period = int_param("rsi", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::rsi::Params { period };
    let out = py
        .detach(|| <trendlib::indicators::rsi::Rsi as Kernel<1, 1>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "RsiStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyRsiStream {
    inner: BarStream<trendlib::indicators::rsi::Rsi, 1, 1>,
}

#[pymethods]
impl PyRsiStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("rsi", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::rsi::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::rsi::Rsi, 1, 1> as Stream>::open([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("rsi", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::rsi::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::rsi::Rsi as Kernel<1, 1>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "rsi"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream rsi bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "sma", signature = (source, *, period))]
pub fn sma<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let source = as_slice(&source, "source")?;
    let period = int_param("sma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::sma::Params { period };
    let out = py
        .detach(|| <trendlib::indicators::sma::Sma as Kernel<1, 1>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "SmaStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PySmaStream {
    inner: BarStream<trendlib::indicators::sma::Sma, 1, 1>,
}

#[pymethods]
impl PySmaStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("sma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::sma::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::sma::Sma, 1, 1> as Stream>::open([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("sma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::sma::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::sma::Sma as Kernel<1, 1>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "sma"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream sma bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "tema", signature = (source, *, period))]
pub fn tema<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let source = as_slice(&source, "source")?;
    let period = int_param("tema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::tema::Params { period };
    let out = py
        .detach(|| <trendlib::indicators::tema::Tema as Kernel<1, 1>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "TemaStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyTemaStream {
    inner: BarStream<trendlib::indicators::tema::Tema, 1, 1>,
}

#[pymethods]
impl PyTemaStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("tema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::tema::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::tema::Tema, 1, 1> as Stream>::open(
                    [source],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("tema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::tema::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::tema::Tema as Kernel<1, 1>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "tema"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream tema bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "trange", signature = (high, low, close))]
pub fn trange<'py>(
    py: Python<'py>,
    high: PyReadonlyArray1<'py, f64>,
    low: PyReadonlyArray1<'py, f64>,
    close: PyReadonlyArray1<'py, f64>,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let high = as_slice(&high, "high")?;
    let low = as_slice(&low, "low")?;
    let close = as_slice(&close, "close")?;
    let params = trendlib::indicators::trange::Params;
    let out = py
        .detach(|| {
            <trendlib::indicators::trange::Trange as Kernel<3, 1>>::batch(
                [high, low, close],
                &params,
            )
        })
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "TrangeStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyTrangeStream {
    inner: BarStream<trendlib::indicators::trange::Trange, 3, 1>,
}

#[pymethods]
impl PyTrangeStream {
    #[staticmethod]
    #[pyo3(signature = (high, low, close))]
    fn open<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
    ) -> PyResult<Self> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let params = trendlib::indicators::trange::Params;
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::trange::Trange, 3, 1> as Stream>::open(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (high, low, close))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let params = trendlib::indicators::trange::Params;
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::trange::Trange as Kernel<3, 1>>::open_and_fill(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (high, low, close))]
    fn update(&mut self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .update([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (high, low, close))]
    fn peek(&self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .peek([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "trange"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream trange bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "willr", signature = (high, low, close, *, period))]
pub fn willr<'py>(
    py: Python<'py>,
    high: PyReadonlyArray1<'py, f64>,
    low: PyReadonlyArray1<'py, f64>,
    close: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let high = as_slice(&high, "high")?;
    let low = as_slice(&low, "low")?;
    let close = as_slice(&close, "close")?;
    let period = int_param("willr", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::willr::Params { period };
    let out = py
        .detach(|| {
            <trendlib::indicators::willr::Willr as Kernel<3, 1>>::batch([high, low, close], &params)
        })
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "WillrStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyWillrStream {
    inner: BarStream<trendlib::indicators::willr::Willr, 3, 1>,
}

#[pymethods]
impl PyWillrStream {
    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("willr", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::willr::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::willr::Willr, 3, 1> as Stream>::open(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("willr", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::willr::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::willr::Willr as Kernel<3, 1>>::open_and_fill(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (high, low, close))]
    fn update(&mut self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .update([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (high, low, close))]
    fn peek(&self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .peek([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "willr"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream willr bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "wma", signature = (source, *, period))]
pub fn wma<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let source = as_slice(&source, "source")?;
    let period = int_param("wma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::wma::Params { period };
    let out = py
        .detach(|| <trendlib::indicators::wma::Wma as Kernel<1, 1>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "WmaStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyWmaStream {
    inner: BarStream<trendlib::indicators::wma::Wma, 1, 1>,
}

#[pymethods]
impl PyWmaStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("wma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::wma::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::wma::Wma, 1, 1> as Stream>::open([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("wma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::wma::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::wma::Wma as Kernel<1, 1>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "wma"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream wma bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(ad, m)?)?;
    m.add_function(wrap_pyfunction!(atr, m)?)?;
    m.add_function(wrap_pyfunction!(cci, m)?)?;
    m.add_function(wrap_pyfunction!(dema, m)?)?;
    m.add_function(wrap_pyfunction!(ema, m)?)?;
    m.add_function(wrap_pyfunction!(macd, m)?)?;
    m.add_function(wrap_pyfunction!(natr, m)?)?;
    m.add_function(wrap_pyfunction!(obv, m)?)?;
    m.add_function(wrap_pyfunction!(roc, m)?)?;
    m.add_function(wrap_pyfunction!(rsi, m)?)?;
    m.add_function(wrap_pyfunction!(sma, m)?)?;
    m.add_function(wrap_pyfunction!(tema, m)?)?;
    m.add_function(wrap_pyfunction!(trange, m)?)?;
    m.add_function(wrap_pyfunction!(willr, m)?)?;
    m.add_function(wrap_pyfunction!(wma, m)?)?;
    m.add_class::<PyAdStream>()?;
    m.add_class::<PyAtrStream>()?;
    m.add_class::<PyCciStream>()?;
    m.add_class::<PyDemaStream>()?;
    m.add_class::<PyEmaStream>()?;
    m.add_class::<PyMacdStream>()?;
    m.add_class::<PyNatrStream>()?;
    m.add_class::<PyObvStream>()?;
    m.add_class::<PyRocStream>()?;
    m.add_class::<PyRsiStream>()?;
    m.add_class::<PySmaStream>()?;
    m.add_class::<PyTemaStream>()?;
    m.add_class::<PyTrangeStream>()?;
    m.add_class::<PyWillrStream>()?;
    m.add_class::<PyWmaStream>()?;
    m.add("PARAMS", params_table(m.py())?)?;
    Ok(())
}

/// Parameter metadata, so the Python layer never repeats a default or a range.
fn params_table<'py>(py: Python<'py>) -> PyResult<Bound<'py, PyDict>> {
    let table = PyDict::new(py);
    {
        let params = PyDict::new(py);
        table.set_item("ad", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 14)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("atr", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 14)?;
            entry.set_item("min", 2)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("cci", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 30)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("dema", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 30)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("ema", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 12)?;
            entry.set_item("min", 2)?;
            entry.set_item("max", 100000)?;
            params.set_item("fast_period", entry)?;
        }
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 26)?;
            entry.set_item("min", 2)?;
            entry.set_item("max", 100000)?;
            params.set_item("slow_period", entry)?;
        }
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 9)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("signal_period", entry)?;
        }
        table.set_item("macd", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 14)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("natr", params)?;
    }
    {
        let params = PyDict::new(py);
        table.set_item("obv", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 10)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("roc", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 14)?;
            entry.set_item("min", 2)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("rsi", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 30)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("sma", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 30)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("tema", params)?;
    }
    {
        let params = PyDict::new(py);
        table.set_item("trange", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 14)?;
            entry.set_item("min", 2)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("willr", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 30)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("wma", params)?;
    }
    Ok(table)
}

pub fn lookback_of(
    py: Python<'_>,
    name: &str,
    params: Option<&Bound<'_, PyDict>>,
) -> PyResult<usize> {
    let get = |key: &str| -> PyResult<Option<i64>> {
        match params.and_then(|p| p.get_item(key).transpose()) {
            Some(value) => Ok(Some(value?.extract()?)),
            None => Ok(None),
        }
    };
    match name {
        "ad" => Ok(<trendlib::indicators::ad::Ad as Kernel<4, 1>>::lookback(
            &trendlib::indicators::ad::Params {},
        )),
        "atr" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("atr", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 14,
            };
            Ok(<trendlib::indicators::atr::Atr as Kernel<3, 1>>::lookback(
                &trendlib::indicators::atr::Params { period },
            ))
        }
        "cci" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("cci", "period", value, 2, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 14,
            };
            Ok(<trendlib::indicators::cci::Cci as Kernel<3, 1>>::lookback(
                &trendlib::indicators::cci::Params { period },
            ))
        }
        "dema" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("dema", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 30,
            };
            Ok(
                <trendlib::indicators::dema::Dema as Kernel<1, 1>>::lookback(
                    &trendlib::indicators::dema::Params { period },
                ),
            )
        }
        "ema" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("ema", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 30,
            };
            Ok(<trendlib::indicators::ema::Ema as Kernel<1, 1>>::lookback(
                &trendlib::indicators::ema::Params { period },
            ))
        }
        "macd" => {
            let fast_period = match get("fast_period")? {
                Some(value) => int_param("macd", "fast_period", value, 2, 100000)
                    .map_err(|e| to_py_err(py, &e))?,
                None => 12,
            };
            let slow_period = match get("slow_period")? {
                Some(value) => int_param("macd", "slow_period", value, 2, 100000)
                    .map_err(|e| to_py_err(py, &e))?,
                None => 26,
            };
            let signal_period = match get("signal_period")? {
                Some(value) => int_param("macd", "signal_period", value, 1, 100000)
                    .map_err(|e| to_py_err(py, &e))?,
                None => 9,
            };
            Ok(
                <trendlib::indicators::macd::Macd as Kernel<1, 3>>::lookback(
                    &trendlib::indicators::macd::Params {
                        fast_period,
                        slow_period,
                        signal_period,
                    },
                ),
            )
        }
        "natr" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("natr", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 14,
            };
            Ok(
                <trendlib::indicators::natr::Natr as Kernel<3, 1>>::lookback(
                    &trendlib::indicators::natr::Params { period },
                ),
            )
        }
        "obv" => Ok(<trendlib::indicators::obv::Obv as Kernel<2, 1>>::lookback(
            &trendlib::indicators::obv::Params {},
        )),
        "roc" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("roc", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 10,
            };
            Ok(<trendlib::indicators::roc::Roc as Kernel<1, 1>>::lookback(
                &trendlib::indicators::roc::Params { period },
            ))
        }
        "rsi" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("rsi", "period", value, 2, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 14,
            };
            Ok(<trendlib::indicators::rsi::Rsi as Kernel<1, 1>>::lookback(
                &trendlib::indicators::rsi::Params { period },
            ))
        }
        "sma" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("sma", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 30,
            };
            Ok(<trendlib::indicators::sma::Sma as Kernel<1, 1>>::lookback(
                &trendlib::indicators::sma::Params { period },
            ))
        }
        "tema" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("tema", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 30,
            };
            Ok(
                <trendlib::indicators::tema::Tema as Kernel<1, 1>>::lookback(
                    &trendlib::indicators::tema::Params { period },
                ),
            )
        }
        "trange" => Ok(
            <trendlib::indicators::trange::Trange as Kernel<3, 1>>::lookback(
                &trendlib::indicators::trange::Params {},
            ),
        ),
        "willr" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("willr", "period", value, 2, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 14,
            };
            Ok(
                <trendlib::indicators::willr::Willr as Kernel<3, 1>>::lookback(
                    &trendlib::indicators::willr::Params { period },
                ),
            )
        }
        "wma" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("wma", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 30,
            };
            Ok(<trendlib::indicators::wma::Wma as Kernel<1, 1>>::lookback(
                &trendlib::indicators::wma::Params { period },
            ))
        }
        other => Err(to_py_err(
            py,
            &TlError::InvalidInput(format!("lookback: no indicator named {other:?}")),
        )),
    }
}
