// @generated by cargo xtask generate — do not edit

use crate::shared::{as_slice, int_param, to_py_err};
use numpy::{IntoPyArray, PyArray1, PyReadonlyArray1};
use pyo3::prelude::*;
use pyo3::types::PyDict;
use trendlib::TlError;
use trendlib::core::kernel::{BarStream, Kernel};
use trendlib::core::traits::Stream;

#[pyfunction]
#[pyo3(name = "atr", signature = (high, low, close, *, period))]
pub fn atr<'py>(
    py: Python<'py>,
    high: PyReadonlyArray1<'py, f64>,
    low: PyReadonlyArray1<'py, f64>,
    close: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let high = as_slice(&high, "high")?;
    let low = as_slice(&low, "low")?;
    let close = as_slice(&close, "close")?;
    let period = int_param("atr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::atr::Params { period };
    let out = py
        .detach(|| {
            <trendlib::indicators::atr::Atr as Kernel<3, 1>>::batch([high, low, close], &params)
        })
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "AtrStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyAtrStream {
    inner: BarStream<trendlib::indicators::atr::Atr, 3, 1>,
}

#[pymethods]
impl PyAtrStream {
    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("atr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::atr::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::atr::Atr, 3, 1> as Stream>::open(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("atr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::atr::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::atr::Atr as Kernel<3, 1>>::open_and_fill(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (high, low, close))]
    fn update(&mut self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .update([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (high, low, close))]
    fn peek(&self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .peek([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "atr"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream atr bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "ema", signature = (source, *, period))]
pub fn ema<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let source = as_slice(&source, "source")?;
    let period = int_param("ema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::ema::Params { period };
    let out = py
        .detach(|| <trendlib::indicators::ema::Ema as Kernel<1, 1>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "EmaStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyEmaStream {
    inner: BarStream<trendlib::indicators::ema::Ema, 1, 1>,
}

#[pymethods]
impl PyEmaStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("ema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::ema::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::ema::Ema, 1, 1> as Stream>::open([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("ema", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::ema::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::ema::Ema as Kernel<1, 1>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "ema"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream ema bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "natr", signature = (high, low, close, *, period))]
pub fn natr<'py>(
    py: Python<'py>,
    high: PyReadonlyArray1<'py, f64>,
    low: PyReadonlyArray1<'py, f64>,
    close: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let high = as_slice(&high, "high")?;
    let low = as_slice(&low, "low")?;
    let close = as_slice(&close, "close")?;
    let period = int_param("natr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::natr::Params { period };
    let out = py
        .detach(|| {
            <trendlib::indicators::natr::Natr as Kernel<3, 1>>::batch([high, low, close], &params)
        })
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "NatrStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyNatrStream {
    inner: BarStream<trendlib::indicators::natr::Natr, 3, 1>,
}

#[pymethods]
impl PyNatrStream {
    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("natr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::natr::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::natr::Natr, 3, 1> as Stream>::open(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (high, low, close, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let period =
            int_param("natr", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::natr::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::natr::Natr as Kernel<3, 1>>::open_and_fill(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (high, low, close))]
    fn update(&mut self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .update([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (high, low, close))]
    fn peek(&self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .peek([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "natr"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream natr bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "rsi", signature = (source, *, period))]
pub fn rsi<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let source = as_slice(&source, "source")?;
    let period = int_param("rsi", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::rsi::Params { period };
    let out = py
        .detach(|| <trendlib::indicators::rsi::Rsi as Kernel<1, 1>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "RsiStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyRsiStream {
    inner: BarStream<trendlib::indicators::rsi::Rsi, 1, 1>,
}

#[pymethods]
impl PyRsiStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("rsi", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::rsi::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::rsi::Rsi, 1, 1> as Stream>::open([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("rsi", "period", period, 2, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::rsi::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::rsi::Rsi as Kernel<1, 1>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "rsi"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream rsi bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "sma", signature = (source, *, period))]
pub fn sma<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let source = as_slice(&source, "source")?;
    let period = int_param("sma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::sma::Params { period };
    let out = py
        .detach(|| <trendlib::indicators::sma::Sma as Kernel<1, 1>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "SmaStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PySmaStream {
    inner: BarStream<trendlib::indicators::sma::Sma, 1, 1>,
}

#[pymethods]
impl PySmaStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("sma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::sma::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::sma::Sma, 1, 1> as Stream>::open([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("sma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::sma::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::sma::Sma as Kernel<1, 1>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "sma"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream sma bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "trange", signature = (high, low, close))]
pub fn trange<'py>(
    py: Python<'py>,
    high: PyReadonlyArray1<'py, f64>,
    low: PyReadonlyArray1<'py, f64>,
    close: PyReadonlyArray1<'py, f64>,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let high = as_slice(&high, "high")?;
    let low = as_slice(&low, "low")?;
    let close = as_slice(&close, "close")?;
    let params = trendlib::indicators::trange::Params;
    let out = py
        .detach(|| {
            <trendlib::indicators::trange::Trange as Kernel<3, 1>>::batch(
                [high, low, close],
                &params,
            )
        })
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "TrangeStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyTrangeStream {
    inner: BarStream<trendlib::indicators::trange::Trange, 3, 1>,
}

#[pymethods]
impl PyTrangeStream {
    #[staticmethod]
    #[pyo3(signature = (high, low, close))]
    fn open<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
    ) -> PyResult<Self> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let params = trendlib::indicators::trange::Params;
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::trange::Trange, 3, 1> as Stream>::open(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (high, low, close))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        high: PyReadonlyArray1<'py, f64>,
        low: PyReadonlyArray1<'py, f64>,
        close: PyReadonlyArray1<'py, f64>,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let high = as_slice(&high, "high")?;
        let low = as_slice(&low, "low")?;
        let close = as_slice(&close, "close")?;
        let params = trendlib::indicators::trange::Params;
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::trange::Trange as Kernel<3, 1>>::open_and_fill(
                    [high, low, close],
                    &params,
                )
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (high, low, close))]
    fn update(&mut self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .update([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (high, low, close))]
    fn peek(&self, py: Python<'_>, high: f64, low: f64, close: f64) -> PyResult<f64> {
        let row = self
            .inner
            .peek([high, low, close])
            .map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "trange"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream trange bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

#[pyfunction]
#[pyo3(name = "wma", signature = (source, *, period))]
pub fn wma<'py>(
    py: Python<'py>,
    source: PyReadonlyArray1<'py, f64>,
    period: i64,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let source = as_slice(&source, "source")?;
    let period = int_param("wma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
    let params = trendlib::indicators::wma::Params { period };
    let out = py
        .detach(|| <trendlib::indicators::wma::Wma as Kernel<1, 1>>::batch([source], &params))
        .map_err(|e| to_py_err(py, &e))?;
    let mut out = out;
    Ok(std::mem::take(&mut out[0]).into_pyarray(py))
}

#[pyclass(module = "trendlib._core", name = "WmaStream", skip_from_py_object)]
#[derive(Clone, Debug)]
pub struct PyWmaStream {
    inner: BarStream<trendlib::indicators::wma::Wma, 1, 1>,
}

#[pymethods]
impl PyWmaStream {
    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<Self> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("wma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::wma::Params { period };
        let inner = py
            .detach(|| {
                <BarStream<trendlib::indicators::wma::Wma, 1, 1> as Stream>::open([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        Ok(Self { inner })
    }

    #[staticmethod]
    #[pyo3(signature = (source, *, period))]
    fn open_and_fill<'py>(
        py: Python<'py>,
        source: PyReadonlyArray1<'py, f64>,
        period: i64,
    ) -> PyResult<(Self, Bound<'py, PyArray1<f64>>)> {
        let source = as_slice(&source, "source")?;
        let period =
            int_param("wma", "period", period, 1, 100000).map_err(|e| to_py_err(py, &e))?;
        let params = trendlib::indicators::wma::Params { period };
        let (inner, out) = py
            .detach(|| {
                <trendlib::indicators::wma::Wma as Kernel<1, 1>>::open_and_fill([source], &params)
            })
            .map_err(|e| to_py_err(py, &e))?;
        let filled = {
            let mut out = out;
            std::mem::take(&mut out[0]).into_pyarray(py)
        };
        Ok((Self { inner }, filled))
    }

    #[pyo3(signature = (source))]
    fn update(&mut self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.update([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    #[pyo3(signature = (source))]
    fn peek(&self, py: Python<'_>, source: f64) -> PyResult<f64> {
        let row = self.inner.peek([source]).map_err(|e| to_py_err(py, &e))?;
        Ok(row[0])
    }

    fn copy(&self) -> Self {
        self.clone()
    }

    #[getter]
    fn value(&self) -> Option<f64> {
        self.inner.value().map(|row| row[0])
    }

    #[getter]
    fn bars_seen(&self) -> u64 {
        self.inner.bars_seen()
    }

    #[getter]
    fn name(&self) -> &'static str {
        "wma"
    }

    fn __repr__(&self) -> String {
        format!(
            "<trendlib stream wma bars_seen={} value={:?}>",
            self.inner.bars_seen(),
            self.inner.value()
        )
    }
}

pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(atr, m)?)?;
    m.add_function(wrap_pyfunction!(ema, m)?)?;
    m.add_function(wrap_pyfunction!(natr, m)?)?;
    m.add_function(wrap_pyfunction!(rsi, m)?)?;
    m.add_function(wrap_pyfunction!(sma, m)?)?;
    m.add_function(wrap_pyfunction!(trange, m)?)?;
    m.add_function(wrap_pyfunction!(wma, m)?)?;
    m.add_class::<PyAtrStream>()?;
    m.add_class::<PyEmaStream>()?;
    m.add_class::<PyNatrStream>()?;
    m.add_class::<PyRsiStream>()?;
    m.add_class::<PySmaStream>()?;
    m.add_class::<PyTrangeStream>()?;
    m.add_class::<PyWmaStream>()?;
    m.add("PARAMS", params_table(m.py())?)?;
    Ok(())
}

/// Parameter metadata, so the Python layer never repeats a default or a range.
fn params_table<'py>(py: Python<'py>) -> PyResult<Bound<'py, PyDict>> {
    let table = PyDict::new(py);
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 14)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("atr", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 30)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("ema", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 14)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("natr", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 14)?;
            entry.set_item("min", 2)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("rsi", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 30)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("sma", params)?;
    }
    {
        let params = PyDict::new(py);
        table.set_item("trange", params)?;
    }
    {
        let params = PyDict::new(py);
        {
            let entry = PyDict::new(py);
            entry.set_item("default", 30)?;
            entry.set_item("min", 1)?;
            entry.set_item("max", 100000)?;
            params.set_item("period", entry)?;
        }
        table.set_item("wma", params)?;
    }
    Ok(table)
}

pub fn lookback_of(
    py: Python<'_>,
    name: &str,
    params: Option<&Bound<'_, PyDict>>,
) -> PyResult<usize> {
    let get = |key: &str| -> PyResult<Option<i64>> {
        match params.and_then(|p| p.get_item(key).transpose()) {
            Some(value) => Ok(Some(value?.extract()?)),
            None => Ok(None),
        }
    };
    match name {
        "atr" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("atr", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 14,
            };
            Ok(<trendlib::indicators::atr::Atr as Kernel<3, 1>>::lookback(
                &trendlib::indicators::atr::Params { period },
            ))
        }
        "ema" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("ema", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 30,
            };
            Ok(<trendlib::indicators::ema::Ema as Kernel<1, 1>>::lookback(
                &trendlib::indicators::ema::Params { period },
            ))
        }
        "natr" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("natr", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 14,
            };
            Ok(
                <trendlib::indicators::natr::Natr as Kernel<3, 1>>::lookback(
                    &trendlib::indicators::natr::Params { period },
                ),
            )
        }
        "rsi" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("rsi", "period", value, 2, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 14,
            };
            Ok(<trendlib::indicators::rsi::Rsi as Kernel<1, 1>>::lookback(
                &trendlib::indicators::rsi::Params { period },
            ))
        }
        "sma" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("sma", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 30,
            };
            Ok(<trendlib::indicators::sma::Sma as Kernel<1, 1>>::lookback(
                &trendlib::indicators::sma::Params { period },
            ))
        }
        "trange" => Ok(
            <trendlib::indicators::trange::Trange as Kernel<3, 1>>::lookback(
                &trendlib::indicators::trange::Params {},
            ),
        ),
        "wma" => {
            let period = match get("period")? {
                Some(value) => {
                    int_param("wma", "period", value, 1, 100000).map_err(|e| to_py_err(py, &e))?
                }
                None => 30,
            };
            Ok(<trendlib::indicators::wma::Wma as Kernel<1, 1>>::lookback(
                &trendlib::indicators::wma::Params { period },
            ))
        }
        other => Err(to_py_err(
            py,
            &TlError::InvalidInput(format!("lookback: no indicator named {other:?}")),
        )),
    }
}
