//! `cargo xtask generate`: everything repetitive, derived from the specs.
//!
//! Nothing here invents a name, a default or a range; all of them come from
//! `spec.yaml`. Output is deterministic - sorted iteration, no timestamps, `\n`
//! endings - so running it twice changes nothing and `regen-check` can tell a
//! stale file from a changed one.

use std::fmt::Write as _;
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use crate::spec::{Param, ParamType, Spec};
use crate::yaml::SpecError;

pub const RUST_BANNER: &str = "// @generated by cargo xtask generate — do not edit";
pub const PY_BANNER: &str = "# @generated by cargo xtask generate — do not edit";

pub struct Generated {
    pub path: PathBuf,
    pub text: String,
}

fn unsupported(spec: &Spec, param: &Param) -> SpecError {
    SpecError::new(
        &spec.path,
        1,
        format!(
            "the generator does not handle parameters of type `{:?}` yet (`{}` is the first to \
             need it); extend crates/xtask/src/generate.rs rather than hand-writing the binding",
            param.ty, param.name
        ),
    )
}

fn check_supported(specs: &[Spec]) -> Result<(), Vec<SpecError>> {
    let mut errors = Vec::new();
    for spec in specs {
        for param in &spec.params {
            if !matches!(param.ty, ParamType::Int | ParamType::Float) {
                errors.push(unsupported(spec, param));
            }
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors)
    }
}

fn py_default(param: &Param) -> String {
    match param.ty {
        ParamType::Int => param.default.clone(),
        ParamType::Float => {
            if param.default.contains('.') || param.default.contains('e') {
                param.default.clone()
            } else {
                format!("{}.0", param.default)
            }
        }
        _ => format!("{:?}", param.default),
    }
}

fn rust_literal(param: &Param, value: &str) -> String {
    match param.ty {
        ParamType::Int => value.to_string(),
        ParamType::Float => {
            if value.contains('.') || value.contains('e') {
                value.to_string()
            } else {
                format!("{value}.0")
            }
        }
        _ => format!("{value:?}"),
    }
}

// ---------------------------------------------------------------- Rust side

/// Only import what the emitted code actually calls, so a generated file never
/// carries an unused import for a parameter type no indicator has yet.
fn helpers_needed(specs: &[Spec]) -> String {
    let mut needed = Vec::new();
    if specs
        .iter()
        .any(|s| s.params.iter().any(|p| p.ty == ParamType::Int))
    {
        needed.push("int_param");
    }
    if specs
        .iter()
        .any(|s| s.params.iter().any(|p| p.ty == ParamType::Float))
    {
        needed.push("float_param");
    }
    needed.sort();
    needed.iter().map(|name| format!("{name}, ")).collect()
}

fn indicators_mod(specs: &[Spec]) -> String {
    let mut out = format!("{RUST_BANNER}\n\n");
    for spec in specs {
        let _ = writeln!(out, "pub mod {};", spec.name);
    }
    out
}

fn bindings(specs: &[Spec]) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "{RUST_BANNER}\n\n\
         use numpy::{{IntoPyArray, PyArray1, PyReadonlyArray1}};\n\
         use pyo3::prelude::*;\n\
         use pyo3::types::PyDict;\n\
         use trendlib::TlError;\n\
         use trendlib::core::kernel::{{BarStream, Kernel}};\n\
         use trendlib::core::traits::Stream;\n\
         use crate::shared::{{as_slice, {helpers}to_py_err}};\n",
        helpers = helpers_needed(specs),
    );

    for spec in specs {
        let name = &spec.name;
        let ty = spec.type_name();
        let inputs = spec.inputs.len();
        let outputs = spec.outputs.len();
        let path = format!("trendlib::indicators::{name}::{ty}");

        let arg_list: String = spec
            .inputs
            .iter()
            .map(|i| format!("{}: PyReadonlyArray1<'py, f64>", i.name))
            .collect::<Vec<_>>()
            .join(",\n    ");
        let param_args: String = spec
            .params
            .iter()
            .map(|p| {
                format!(
                    ",\n    {}: {}",
                    p.name,
                    match p.ty {
                        ParamType::Int => "i64",
                        _ => "f64",
                    }
                )
            })
            .collect();
        let signature_params: String = spec
            .params
            .iter()
            .map(|p| format!(", {}", p.name))
            .collect::<Vec<_>>()
            .join("");
        let signature_inputs: String = spec
            .inputs
            .iter()
            .map(|i| i.name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        let signature = if spec.params.is_empty() {
            format!("({signature_inputs})")
        } else {
            format!("({signature_inputs}, *{signature_params})")
        };

        let build_params = params_builder(spec);
        let borrow: String = spec
            .inputs
            .iter()
            .map(|i| format!("    let {0} = as_slice(&{0}, \"{0}\")?;\n", i.name))
            .collect();
        let columns: String = spec
            .inputs
            .iter()
            .map(|i| i.name.clone())
            .collect::<Vec<_>>()
            .join(", ");

        let wrap = wrap_outputs(spec);
        let return_type = if outputs == 1 {
            "Bound<'py, PyArray1<f64>>".to_string()
        } else {
            let each: Vec<&str> = spec
                .outputs
                .iter()
                .map(|o| {
                    if o.dtype == "int32" {
                        "Bound<'py, PyArray1<i32>>"
                    } else {
                        "Bound<'py, PyArray1<f64>>"
                    }
                })
                .collect();
            format!("({})", each.join(", "))
        };
        let return_type = if outputs == 1 && spec.outputs[0].dtype == "int32" {
            "Bound<'py, PyArray1<i32>>".to_string()
        } else {
            return_type
        };

        // A tuple of several arrays is too wide to repeat at four call sites,
        // so a multi-output indicator gets a named alias for it.
        let mut alias = String::new();
        let return_type = if outputs == 1 {
            return_type
        } else {
            let named = format!("{ty}Outputs");
            let _ = write!(alias, "\ntype {named}<'py> = {return_type};\n");
            format!("{named}<'py>")
        };
        out.push_str(&alias);

        let _ = write!(
            out,
            "\n\
             #[pyfunction]\n\
             #[pyo3(name = \"{name}\", signature = {signature})]\n\
             pub fn {name}<'py>(\n    py: Python<'py>,\n    {arg_list}{param_args},\n) -> PyResult<{return_type}> {{\n\
             {borrow}{build_params}\
             \x20   let out = py\n        .detach(|| <{path} as Kernel<{inputs}, {outputs}>>::batch([{columns}], &params))\n        .map_err(|e| to_py_err(py, &e))?;\n\
             {wrap}\
             }}\n"
        );

        let stream_class = spec.py_stream_class();
        let update_args: String = spec
            .inputs
            .iter()
            .map(|i| format!(", {}: f64", i.name))
            .collect();
        let bar = format!(
            "[{}]",
            spec.inputs
                .iter()
                .map(|i| i.name.clone())
                .collect::<Vec<_>>()
                .join(", ")
        );
        let value_wrap = stream_value(spec);
        let update_signature = format!(
            "({})",
            spec.inputs
                .iter()
                .map(|i| i.name.clone())
                .collect::<Vec<_>>()
                .join(", ")
        );

        let _ = write!(
            out,
            "\n\
             #[pyclass(module = \"trendlib._core\", name = \"{stream_class}\", skip_from_py_object)]\n\
             #[derive(Clone, Debug)]\n\
             pub struct Py{stream_class} {{\n    inner: BarStream<{path}, {inputs}, {outputs}>,\n}}\n\
             \n\
             #[pymethods]\n\
             impl Py{stream_class} {{\n\
             \x20   #[staticmethod]\n\
             \x20   #[pyo3(signature = {signature})]\n\
             \x20   fn open<'py>(\n        py: Python<'py>,\n        {arg_list}{param_args},\n    ) -> PyResult<Self> {{\n\
             {borrow}{build_params}\
             \x20       let inner = py\n            .detach(|| <BarStream<{path}, {inputs}, {outputs}> as Stream>::open([{columns}], &params))\n            .map_err(|e| to_py_err(py, &e))?;\n        Ok(Self {{ inner }})\n    }}\n\
             \n\
             \x20   #[staticmethod]\n\
             \x20   #[pyo3(signature = {signature})]\n\
             \x20   fn open_and_fill<'py>(\n        py: Python<'py>,\n        {arg_list}{param_args},\n    ) -> PyResult<(Self, {return_type})> {{\n\
             {borrow}{build_params}\
             \x20       let (inner, out) = py\n            .detach(|| <{path} as Kernel<{inputs}, {outputs}>>::open_and_fill([{columns}], &params))\n            .map_err(|e| to_py_err(py, &e))?;\n        let filled = {{\n{}        }};\n        Ok((Self {{ inner }}, filled))\n    }}\n\
             \n\
             \x20   #[pyo3(signature = {update_signature})]\n\
             \x20   fn update(&mut self, py: Python<'_>{update_args}) -> PyResult<{py_value}> {{\n        let row = self.inner.update({bar}).map_err(|e| to_py_err(py, &e))?;\n        Ok({value_wrap})\n    }}\n\
             \n\
             \x20   #[pyo3(signature = {update_signature})]\n\
             \x20   fn peek(&self, py: Python<'_>{update_args}) -> PyResult<{py_value}> {{\n        let row = self.inner.peek({bar}).map_err(|e| to_py_err(py, &e))?;\n        Ok({value_wrap})\n    }}\n\
             \n\
             \x20   fn copy(&self) -> Self {{\n        self.clone()\n    }}\n\
             \n\
             \x20   #[getter]\n    fn value(&self) -> Option<{py_value}> {{\n        self.inner.value().map(|row| {value_wrap})\n    }}\n\
             \n\
             \x20   #[getter]\n    fn bars_seen(&self) -> u64 {{\n        self.inner.bars_seen()\n    }}\n\
             \n\
             \x20   #[getter]\n    fn name(&self) -> &'static str {{\n        \"{name}\"\n    }}\n\
             \n\
             \x20   fn __repr__(&self) -> String {{\n        format!(\n            \"<trendlib stream {name} bars_seen={{}} value={{:?}}>\",\n            self.inner.bars_seen(),\n            self.inner.value()\n        )\n    }}\n}}\n",
            indent_block(&format!("let mut out = out;\n{}", wrap_in_place(spec)), 12),
            py_value = py_value_type(spec),
        );
    }

    let _ = write!(out, "\n{}", registration(specs));
    out
}

fn py_value_type(spec: &Spec) -> String {
    if spec.outputs.len() == 1 {
        if spec.outputs[0].dtype == "int32" {
            "i32"
        } else {
            "f64"
        }
        .to_string()
    } else {
        format!(
            "({})",
            spec.outputs
                .iter()
                .map(|o| if o.dtype == "int32" { "i32" } else { "f64" })
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn stream_value(spec: &Spec) -> String {
    if spec.outputs.len() == 1 {
        if spec.outputs[0].dtype == "int32" {
            "row[0] as i32".to_string()
        } else {
            "row[0]".to_string()
        }
    } else {
        format!(
            "({})",
            spec.outputs
                .iter()
                .enumerate()
                .map(|(index, o)| if o.dtype == "int32" {
                    format!("row[{index}] as i32")
                } else {
                    format!("row[{index}]")
                })
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn column_expr(index: usize, dtype: &str, source: &str) -> String {
    if dtype == "int32" {
        format!(
            "{source}[{index}].iter().map(|v| if v.is_nan() {{ 0 }} else {{ *v as i32 }}).collect::<Vec<i32>>().into_pyarray(py)"
        )
    } else {
        format!("std::mem::take(&mut {source}[{index}]).into_pyarray(py)")
    }
}

fn wrap_outputs(spec: &Spec) -> String {
    let body = wrap_in_place(spec);
    format!(
        "    let mut out = out;\n{}",
        indent_block(&format!("Ok({body})"), 4)
    )
}

fn wrap_in_place(spec: &Spec) -> String {
    let mut parts: Vec<String> = Vec::new();
    for (index, output) in spec.outputs.iter().enumerate() {
        parts.push(column_expr(index, &output.dtype, "out"));
    }
    if parts.len() == 1 {
        parts.pop().unwrap()
    } else {
        format!("(\n    {},\n)", parts.join(",\n    "))
    }
}

fn indent_block(text: &str, spaces: usize) -> String {
    let pad = " ".repeat(spaces);
    text.lines()
        .map(|line| {
            if line.is_empty() {
                String::from("\n")
            } else {
                format!("{pad}{line}\n")
            }
        })
        .collect()
}

fn params_builder(spec: &Spec) -> String {
    let path = format!("trendlib::indicators::{}", spec.name);
    if spec.params.is_empty() {
        return format!("    let params = {path}::Params;\n");
    }
    let mut out = String::new();
    for param in &spec.params {
        let check = match param.ty {
            ParamType::Int => format!(
                "    let {0} = int_param(\"{1}\", \"{0}\", {0}, {2}, {3}).map_err(|e| to_py_err(py, &e))?;\n",
                param.name,
                spec.name,
                param.min.clone().unwrap_or_else(|| "0".into()),
                param.max.clone().unwrap_or_else(|| "i64::MAX".into()),
            ),
            _ => format!(
                "    let {0} = float_param(\"{1}\", \"{0}\", {0}, {2}, {3}).map_err(|e| to_py_err(py, &e))?;\n",
                param.name,
                spec.name,
                param
                    .min
                    .as_ref()
                    .map(|v| rust_literal(param, v))
                    .unwrap_or_else(|| "f64::NEG_INFINITY".into()),
                param
                    .max
                    .as_ref()
                    .map(|v| rust_literal(param, v))
                    .unwrap_or_else(|| "f64::INFINITY".into()),
            ),
        };
        out.push_str(&check);
    }
    let fields: String = spec
        .params
        .iter()
        .map(|p| format!("{}, ", p.name))
        .collect();
    let _ = writeln!(out, "    let params = {path}::Params {{ {fields}}};");
    out
}

fn registration(specs: &[Spec]) -> String {
    let mut out = String::from("pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {\n");
    for spec in specs {
        let _ = writeln!(
            out,
            "    m.add_function(wrap_pyfunction!({}, m)?)?;",
            spec.name
        );
    }
    for spec in specs {
        let _ = writeln!(out, "    m.add_class::<Py{}>()?;", spec.py_stream_class());
    }
    out.push_str("    m.add(\"PARAMS\", params_table(m.py())?)?;\n    Ok(())\n}\n\n");

    out.push_str(
        "/// Parameter metadata, so the Python layer never repeats a default or a range.\n\
         fn params_table<'py>(py: Python<'py>) -> PyResult<Bound<'py, PyDict>> {\n\
         \x20   let table = PyDict::new(py);\n",
    );
    for spec in specs {
        let _ = writeln!(out, "    {{\n        let params = PyDict::new(py);");
        for param in &spec.params {
            let _ = writeln!(
                out,
                "        {{\n            let entry = PyDict::new(py);\n            entry.set_item(\"default\", {})?;\n            entry.set_item(\"min\", {})?;\n            entry.set_item(\"max\", {})?;\n            params.set_item(\"{}\", entry)?;\n        }}",
                rust_literal(param, &param.default),
                param
                    .min
                    .as_ref()
                    .map(|v| rust_literal(param, v))
                    .unwrap_or_else(|| "py.None()".into()),
                param
                    .max
                    .as_ref()
                    .map(|v| rust_literal(param, v))
                    .unwrap_or_else(|| "py.None()".into()),
                param.name
            );
        }
        let _ = writeln!(
            out,
            "        table.set_item(\"{}\", params)?;\n    }}",
            spec.name
        );
    }
    out.push_str("    Ok(table)\n}\n\n");
    out.push_str(&lookback_table(specs));
    out
}

/// `tl.lookback(name, **params)` without a registry: a match over the specs,
/// with each parameter read from the keyword dict or left at its default.
fn lookback_table(specs: &[Spec]) -> String {
    let mut out = String::from(
        "pub fn lookback_of(\n    py: Python<'_>,\n    name: &str,\n    params: Option<&Bound<'_, PyDict>>,\n) -> PyResult<usize> {\n         \x20   let get = |key: &str| -> PyResult<Option<i64>> {\n        match params.and_then(|p| p.get_item(key).transpose()) {\n            Some(value) => Ok(Some(value?.extract()?)),\n            None => Ok(None),\n        }\n    };\n         \x20   match name {\n",
    );
    for spec in specs {
        let path = format!("trendlib::indicators::{}", spec.name);
        let ty = format!("{path}::{}", spec.type_name());
        let mut body = String::new();
        for param in &spec.params {
            let _ = write!(
                body,
                "            let {0} = match get(\"{0}\")? {{\n                Some(value) => int_param(\"{1}\", \"{0}\", value, {2}, {3}).map_err(|e| to_py_err(py, &e))?,\n                None => {4},\n            }};\n",
                param.name,
                spec.name,
                param.min.clone().unwrap_or_else(|| "0".into()),
                param.max.clone().unwrap_or_else(|| "i64::MAX".into()),
                param.default,
            );
        }
        let fields: String = spec
            .params
            .iter()
            .map(|p| format!("{}, ", p.name))
            .collect();
        let _ = write!(
            out,
            "        \"{}\" => {{\n{body}            Ok(<{ty} as Kernel<{}, {}>>::lookback(&{path}::Params {{ {fields}}}))\n        }}\n",
            spec.name,
            spec.inputs.len(),
            spec.outputs.len(),
        );
    }
    out.push_str(
        "        other => Err(to_py_err(\n            py,\n            &TlError::InvalidInput(format!(\"lookback: no indicator named {other:?}\")),\n        )),\n    }\n}\n",
    );
    out
}

// -------------------------------------------------------------- Python side

fn functions(specs: &[Spec]) -> String {
    let mut out = format!(
        "{PY_BANNER}\n\"\"\"Batch functions and their TA-Lib aliases.\n\n\
         One wrapper per indicator, generated from its spec.yaml. Defaults come\n\
         from the extension module rather than being repeated here, so there is\n\
         one place they can be wrong.\n\"\"\"\n\n\
         from __future__ import annotations\n\n\
         from typing import Any\n\n\
         from trendlib import _convert, _core\n\n"
    );

    let mut exported: Vec<String> = Vec::new();
    for spec in specs {
        exported.push(format!("{:?}", spec.name));
        if let Some(alias) = &spec.talib {
            exported.push(format!("{:?}", alias.name));
        }
    }
    exported.push("\"lookback\"".to_string());
    exported.sort();
    let _ = writeln!(out, "__all__ = [\n    {},\n]\n", exported.join(",\n    "));
    out.push_str("_PARAMS = _core.PARAMS\n\n\n");

    for spec in specs {
        let args: Vec<String> = spec
            .inputs
            .iter()
            .map(|i| format!("{} = None", i.name))
            .collect();
        let params: Vec<String> = spec
            .params
            .iter()
            .map(|p| {
                format!(
                    "{}: {} = _PARAMS[{:?}][{:?}][\"default\"]",
                    p.name,
                    if p.ty == ParamType::Int {
                        "int"
                    } else {
                        "float"
                    },
                    spec.name,
                    p.name
                )
            })
            .collect();
        let signature = if params.is_empty() {
            args.join(", ")
        } else {
            format!("{}, *, {}", args.join(", "), params.join(", "))
        };
        let names: String = spec
            .inputs
            .iter()
            .map(|i| format!("{:?}", i.name))
            .collect::<Vec<_>>()
            .join(", ");
        let kinds: String = spec
            .inputs
            .iter()
            .map(|i| format!("{:?}", i.kind))
            .collect::<Vec<_>>()
            .join(", ");
        let call_params: String = spec
            .params
            .iter()
            .map(|p| format!(", {0}={0}", p.name))
            .collect();
        let out_names: String = spec
            .outputs
            .iter()
            .map(|o| format!("{:?}", o.name))
            .collect::<Vec<_>>()
            .join(", ");

        let mut doc = String::new();
        let _ = writeln!(doc, "{}.", spec.title);
        if !spec.params.is_empty() {
            doc.push_str("\n    Parameters\n    ----------\n");
            for param in &spec.params {
                let range = match (&param.min, &param.max) {
                    (Some(low), Some(high)) => format!(", from {low} to {high}"),
                    _ => String::new(),
                };
                let _ = write!(
                    doc,
                    "    {} : {}, default {}\n        {}{}.\n",
                    param.name,
                    if param.ty == ParamType::Int {
                        "int"
                    } else {
                        "float"
                    },
                    py_default(param),
                    param.doc,
                    range
                );
            }
        }
        doc.push_str("\n    Returns\n    -------\n    ");
        if spec.outputs.len() == 1 {
            let _ = write!(
                doc,
                "ndarray or Series\n        {}.\n    ",
                spec.outputs[0].doc
            );
        } else {
            doc.push_str("tuple of ndarray, or DataFrame\n");
            for output in &spec.outputs {
                let _ = writeln!(doc, "        {}: {}.", output.name, output.doc);
            }
            doc.push_str("    ");
        }

        let coerce: String = spec
            .params
            .iter()
            .map(|p| match p.ty {
                ParamType::Int => format!(
                    "    {0} = _convert.as_int({1:?}, {0:?}, {0})\n",
                    p.name, spec.name
                ),
                _ => format!(
                    "    {0} = _convert.as_float({1:?}, {0:?}, {0})\n",
                    p.name, spec.name
                ),
            })
            .collect();

        let _ = write!(
            out,
            "def {name}({signature}) -> Any:\n    \"\"\"{doc}\"\"\"\n\
             {coerce}\
             \x20   columns, carrier = _convert.bars({name:?}, ({inputs_tuple}), ({names},), ({kinds},))\n\
             \x20   out = _core.{name}(*columns{call_params})\n\
             \x20   return _convert.wrap_outputs(out, carrier, ({out_names},))\n\n\n",
            name = spec.name,
            inputs_tuple = spec
                .inputs
                .iter()
                .map(|i| i.name.clone())
                .collect::<Vec<_>>()
                .join(", ")
                + if spec.inputs.len() == 1 { "," } else { "" },
        );
    }

    out.push_str(
        "def lookback(name: str, **params: Any) -> int:\n\
         \x20   \"\"\"Warm-up rows before the first defined value.\"\"\"\n\
         \x20   known = _PARAMS.get(name)\n\
         \x20   if known is None:\n\
         \x20       raise _convert.InvalidInput(f\"lookback: no indicator named {name!r}\")\n\
         \x20   unknown = set(params) - set(known)\n\
         \x20   if unknown:\n\
         \x20       raise TypeError(f\"lookback: {name} has no parameter {sorted(unknown)[0]!r}\")\n\
         \x20   return _core.lookback(name, **params)\n\n\n",
    );

    for spec in specs {
        let Some(alias) = &spec.talib else { continue };
        let renamed: Vec<String> = spec
            .params
            .iter()
            .map(|p| {
                let theirs = alias.params.get(&p.name).cloned().unwrap_or(p.name.clone());
                format!(
                    "{theirs}: {} = _PARAMS[{:?}][{:?}][\"default\"]",
                    if p.ty == ParamType::Int {
                        "int"
                    } else {
                        "float"
                    },
                    spec.name,
                    p.name
                )
            })
            .collect();
        let forwarded: Vec<String> = spec
            .params
            .iter()
            .map(|p| {
                let theirs = alias.params.get(&p.name).cloned().unwrap_or(p.name.clone());
                format!("{}={theirs}", p.name)
            })
            .collect();
        let args: Vec<String> = spec.inputs.iter().map(|i| i.name.clone()).collect();
        let signature = if renamed.is_empty() {
            args.join(", ")
        } else {
            format!("{}, {}", args.join(", "), renamed.join(", "))
        };
        let call = if forwarded.is_empty() {
            args.join(", ")
        } else {
            format!("{}, {}", args.join(", "), forwarded.join(", "))
        };
        let _ = write!(
            out,
            "def {}({signature}) -> Any:\n    \"\"\"TA-Lib-style alias for :func:`{}`.\"\"\"\n    return {}({call})\n\n\n",
            alias.name, spec.name, spec.name
        );
    }

    out.trim_end().to_string() + "\n"
}

fn streams(specs: &[Spec]) -> String {
    let mut out = format!(
        "{PY_BANNER}\n\"\"\"Live indicator values, one factory per indicator.\n\n\
         A stream is a value, not a session: it holds no global state, `copy` is\n\
         an independent fork, and what it returns is bitwise identical to running\n\
         the batch function over the whole extended series.\n\"\"\"\n\n\
         from __future__ import annotations\n\n\
         from typing import Any\n\n\
         from trendlib import _convert, _core\n\
         from trendlib._stream_base import Factory\n\n"
    );
    let names: Vec<String> = specs.iter().map(|s| format!("{:?}", s.name)).collect();
    let _ = writeln!(out, "__all__ = [\n    {},\n]\n", names.join(",\n    "));
    for spec in specs {
        let names: String = spec
            .inputs
            .iter()
            .map(|i| format!("{:?}", i.name))
            .collect::<Vec<_>>()
            .join(", ");
        let kinds: String = spec
            .inputs
            .iter()
            .map(|i| format!("{:?}", i.kind))
            .collect::<Vec<_>>()
            .join(", ");
        let outs: String = spec
            .outputs
            .iter()
            .map(|o| format!("{:?}", o.name))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "{name} = Factory({name:?}, _core.{cls}, ({names},), ({kinds},), ({outs},))",
            name = spec.name,
            cls = spec.py_stream_class(),
        );
    }
    let _ = writeln!(out, "\n_ = (Any, _convert)");
    out
}

fn stubs(specs: &[Spec]) -> String {
    let mut out = format!(
        "{PY_BANNER}\nfrom typing import Any\n\nimport numpy as np\n\n__version__: str\nPARAMS: dict[str, dict[str, dict[str, Any]]]\n\ndef lookback(name: str, **params: Any) -> int: ...\n"
    );
    for spec in specs {
        let args: Vec<String> = spec
            .inputs
            .iter()
            .map(|i| format!("{}: np.ndarray", i.name))
            .collect();
        let params: Vec<String> = spec
            .params
            .iter()
            .map(|p| {
                format!(
                    "{}: {}",
                    p.name,
                    if p.ty == ParamType::Int {
                        "int"
                    } else {
                        "float"
                    }
                )
            })
            .collect();
        let signature = if params.is_empty() {
            args.join(", ")
        } else {
            format!("{}, *, {}", args.join(", "), params.join(", "))
        };
        let returns = if spec.outputs.len() == 1 {
            "np.ndarray".to_string()
        } else {
            format!(
                "tuple[{}]",
                spec.outputs
                    .iter()
                    .map(|_| "np.ndarray")
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        };
        let _ = writeln!(out, "def {}({signature}) -> {returns}: ...", spec.name);
    }
    for spec in specs {
        let _ = writeln!(
            out,
            // A stub is never evaluated, so a forward reference needs no quotes.
            "\nclass {}:\n    @staticmethod\n    def open(*args: Any, **params: Any) -> {}: ...\n    @staticmethod\n    def open_and_fill(*args: Any, **params: Any) -> tuple[{}, Any]: ...\n    def update(self, *bar: float) -> Any: ...\n    def peek(self, *bar: float) -> Any: ...\n    def copy(self) -> {}: ...\n    @property\n    def value(self) -> Any: ...\n    @property\n    def bars_seen(self) -> int: ...\n    @property\n    def name(self) -> str: ...",
            spec.py_stream_class(),
            spec.py_stream_class(),
            spec.py_stream_class(),
            spec.py_stream_class()
        );
    }
    out
}

/// Pipe text through a formatter.
///
/// Formatting is required, not best-effort. If it were optional, a machine
/// without the tool would generate different bytes from one with it and
/// `regen-check` would fail for everyone downstream, which is a worse failure
/// than a missing tool reported plainly here.
fn format_with(program: &str, args: &[&str], text: &str, what: &Path) -> Result<String, SpecError> {
    let mut child = Command::new(program)
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| {
            SpecError::new(
                what,
                1,
                format!(
                    "cannot run `{program}` to format generated code ({error}). \
                     rustfmt comes with the pinned toolchain and ruff is in the dev extra: \
                     `pip install -e '.[dev]'`"
                ),
            )
        })?;
    child
        .stdin
        .take()
        .expect("stdin was piped")
        .write_all(text.as_bytes())
        .map_err(|error| SpecError::new(what, 1, format!("writing to {program}: {error}")))?;
    let output = child
        .wait_with_output()
        .map_err(|error| SpecError::new(what, 1, format!("running {program}: {error}")))?;
    if !output.status.success() {
        return Err(SpecError::new(
            what,
            1,
            format!(
                "{program} rejected the generated code: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            ),
        ));
    }
    String::from_utf8(output.stdout)
        .map_err(|error| SpecError::new(what, 1, format!("{program} output: {error}")))
}

fn formatted(path: &Path, text: &str) -> Result<String, SpecError> {
    match path.extension().and_then(|e| e.to_str()) {
        Some("rs") => format_with("rustfmt", &["--edition", "2024"], text, path),
        Some("py") | Some("pyi") => {
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("x.py");
            format_with(
                "ruff",
                &["format", "--stdin-filename", name, "-"],
                text,
                path,
            )
        }
        _ => Ok(text.to_string()),
    }
}

/// The table the Rust test suites iterate.
///
/// Generated rather than hand-written because every indicator has to appear in
/// it or it is simply untested, and a list people maintain by hand is a list
/// that silently falls behind. Parameters travel as `f64` in spec order so one
/// signature covers an indicator with no parameters and one with three.
fn test_registry(specs: &[Spec]) -> String {
    let mut out = format!(
        "{RUST_BANNER}\n\n\
         #![allow(dead_code)]\n\n\
         use super::{{AnyStream, Columns, OpenAndFillResult, ParamSpec, Registered, TlError}};\n\
         use trendlib::core::kernel::Kernel;\n\n"
    );

    for spec in specs {
        let name = &spec.name;
        let path = format!("trendlib::indicators::{name}");
        let inputs = spec.inputs.len();
        let outputs = spec.outputs.len();

        let fields: String = spec
            .params
            .iter()
            .enumerate()
            .map(|(index, param)| match param.ty {
                ParamType::Int => format!("{}: values[{index}] as usize, ", param.name),
                _ => format!("{}: values[{index}], ", param.name),
            })
            .collect();
        let build = if spec.params.is_empty() {
            format!("        let _ = values;\n        {path}::Params\n")
        } else {
            format!("        {path}::Params {{ {fields}}}\n")
        };

        let param_specs: String = spec
            .params
            .iter()
            .map(|param| {
                format!(
                    "        ParamSpec {{ name: {:?}, default: {}, min: {}, max: {}, integral: {} }},\n",
                    param.name,
                    as_float(&param.default),
                    param
                        .min
                        .as_deref()
                        .map(as_float)
                        .unwrap_or_else(|| "f64::NEG_INFINITY".into()),
                    param
                        .max
                        .as_deref()
                        .map(as_float)
                        .unwrap_or_else(|| "f64::INFINITY".into()),
                    param.ty == ParamType::Int,
                )
            })
            .collect();

        let _ = write!(
            out,
            "mod {name}_adapter {{\n\
             \x20   use super::*;\n\n\
             \x20   type Indicated = {path}::{ty};\n\
             \x20   const INPUTS: usize = {inputs};\n\
             \x20   const OUTPUTS: usize = {outputs};\n\n\
             \x20   const PARAMS: &[ParamSpec] = &[\n{param_specs}    ];\n\n\
             \x20   fn params(values: &[f64]) -> {path}::Params {{\n{build}    }}\n\n\
             \x20   fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {{\n\
             \x20       assert_eq!(inputs.len(), INPUTS, \"{name} takes {{INPUTS}} inputs\");\n\
             \x20       std::array::from_fn(|i| inputs[i])\n    }}\n\n\
             \x20   fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {{\n\
             \x20       <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))\n            .map(|out| out.to_vec())\n    }}\n\n\
             \x20   fn lookback(values: &[f64]) -> usize {{\n\
             \x20       <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))\n    }}\n\n\
             \x20   fn open_and_fill(\n        inputs: &[&[f64]],\n        values: &[f64],\n    ) -> OpenAndFillResult {{\n\
             \x20       let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(\n            columns(inputs),\n            &params(values),\n        )?;\n\
             \x20       Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))\n    }}\n\n\
             \x20   pub fn registered() -> Registered {{\n\
             \x20       Registered {{\n\
             \x20           name: {path}::NAME,\n\
             \x20           inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,\n\
             \x20           outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,\n\
             \x20           params: PARAMS,\n\
             \x20           batch,\n            lookback,\n            open_and_fill,\n        }}\n    }}\n}}\n\n",
            ty = spec.type_name(),
        );
    }

    out.push_str("pub fn registered() -> Vec<Registered> {\n    vec![\n");
    for spec in specs {
        let _ = writeln!(out, "        {}_adapter::registered(),", spec.name);
    }
    out.push_str("    ]\n}\n");
    out
}

fn as_float(value: &str) -> String {
    if value.contains('.') || value.contains('e') {
        value.to_string()
    } else {
        format!("{value}.0")
    }
}

pub fn generate(root: &Path) -> Result<Vec<Generated>, Vec<SpecError>> {
    let indicators = root.join("crates/trendlib/src/indicators");
    let specs = crate::spec::read_all(&indicators)?;
    check_supported(&specs)?;

    let raw = vec![
        (indicators.join("mod.rs"), indicators_mod(&specs)),
        (
            root.join("crates/trendlib-py/src/generated.rs"),
            bindings(&specs),
        ),
        (
            root.join("python/trendlib/_functions.py"),
            functions(&specs),
        ),
        (root.join("python/trendlib/stream.py"), streams(&specs)),
        (root.join("python/trendlib/_core.pyi"), stubs(&specs)),
        (
            root.join("crates/trendlib/tests/support/registry.rs"),
            test_registry(&specs),
        ),
    ];

    let mut generated = Vec::new();
    let mut errors = Vec::new();
    for (path, text) in raw {
        match formatted(&path, &text) {
            Ok(text) => generated.push(Generated { path, text }),
            Err(error) => errors.push(error),
        }
    }
    if errors.is_empty() {
        Ok(generated)
    } else {
        Err(errors)
    }
}

pub fn write_all(generated: &[Generated]) -> std::io::Result<Vec<PathBuf>> {
    let mut written = Vec::new();
    for item in generated {
        if let Some(parent) = item.path.parent() {
            fs::create_dir_all(parent)?;
        }
        let current = fs::read_to_string(&item.path).unwrap_or_default();
        if current != item.text {
            fs::write(&item.path, &item.text)?;
            written.push(item.path.clone());
        }
    }
    Ok(written)
}
