"""Write docs/PROGRESS.md: every indicator, one per line, ticked when it ships.

    python scripts/catalogue/progress.py --write
    python scripts/catalogue/progress.py --check

The marks are read off the repository, never typed by hand, so the list cannot
claim something is done that is not. An indicator counts as done when its folder
holds all four files `docs/SPEC_FORMAT.md` requires - `spec.yaml`, `mod.rs`,
`doc.md` and at least one golden CSV - and its name is reachable from the Python
API. An indicator whose core is written but whose binding the generator has not
produced yet is marked "core only", because a number nobody can call is not
shipped.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CATALOGUE = REPO_ROOT / "docs" / "INDICATORS_TALIB.md"
INDICATORS = REPO_ROOT / "crates" / "trendlib" / "src" / "indicators"
FUNCTIONS = REPO_ROOT / "python" / "trendlib" / "_functions.py"
PROGRESS = REPO_ROOT / "docs" / "PROGRESS.md"

BANNER = "@generated by scripts/catalogue/progress.py -- do not edit"

ROW = re.compile(r"^\| `([a-z0-9_]+)`(?: &dagger;)? \| `([A-Z0-9_]+)` \|")
HEADING = re.compile(r"^## (.+)$")

# The indicators TrendLib defines itself, which have no catalogue row because
# TA-Lib has no equivalent (`docs/INDICATORS.md` section 3).
OWN = [
    ("Levels", "cpr", "Central Pivot Range"),
    ("Levels", "pivots_traditional", "Traditional floor pivots"),
    ("Levels", "pivots_camarilla", "Camarilla pivots"),
]

# The chart patterns, approved on top of the catalogue and checked against a
# second oracle (`docs/INDICATORS.md` section 5.1). Read from that table rather
# than listed here, so approving one more is one edit, in the document.
CHART_ROW = re.compile(r"^\| `(chart_[a-z0-9_]+)` \| ([^|]+?) \|")


def chart_entries() -> list[tuple[str, str, str]]:
    """`(group title, trendlib name, title)` for every approved chart pattern."""
    text = (REPO_ROOT / "docs" / "INDICATORS.md").read_text(encoding="utf-8")
    section = text.split("### 5.1 Chart patterns", 1)[1]
    return [
        ("Chart patterns", row.group(1), row.group(2).strip())
        for line in section.splitlines()
        if (row := CHART_ROW.match(line))
    ]

# The slice the first public release ships (`docs/INDICATORS.md` section 2.1).
RELEASE_SET = {
    "sma",
    "ema",
    "wma",
    "dema",
    "tema",
    "bbands",
    "supertrend",
    "rsi",
    "macd",
    "stoch",
    "adx",
    "cci",
    "roc",
    "willr",
    "trange",
    "atr",
    "natr",
    "obv",
    "ad",
    "adosc",
    "vwap",
    "cpr",
    "pivots_traditional",
    "pivots_camarilla",
    "cdl_doji",
    "cdl_engulfing",
    "cdl_hammer",
}


def catalogue_entries() -> list[tuple[str, str, str]]:
    """`(group title, trendlib name, talib name)` in catalogue order."""
    entries = []
    group = ""
    for line in CATALOGUE.read_text(encoding="utf-8").splitlines():
        heading = HEADING.match(line)
        if heading:
            group = heading.group(1)
            continue
        row = ROW.match(line)
        if row:
            entries.append((group, row.group(1), row.group(2)))
    return entries


def titles() -> dict[str, str]:
    """Display titles, taken from each folder's spec where one exists."""
    found = {}
    for spec in INDICATORS.glob("*/spec.yaml"):
        for line in spec.read_text(encoding="utf-8").splitlines():
            if line.startswith("title: "):
                found[spec.parent.name] = line[len("title: ") :].strip()
                break
    return found


def state_of(name: str, in_python: set[str]) -> str:
    folder = INDICATORS / name
    required = [folder / "spec.yaml", folder / "mod.rs", folder / "doc.md"]
    if not all(path.is_file() for path in required):
        return "todo"
    if not list((folder / "golden").glob("*.csv")):
        return "todo"
    return "done" if name in in_python else "core"


def python_surface() -> set[str]:
    if not FUNCTIONS.is_file():
        return set()
    return set(re.findall(r"^def ([a-z][a-z0-9_]*)\(", FUNCTIONS.read_text(encoding="utf-8"), re.M))


MARK = {"done": "[x]", "core": "[~]", "todo": "[ ]"}
SUFFIX = {"done": "", "core": " -- core only, no Python binding yet", "todo": ""}


def render() -> str:
    in_python = python_surface()
    known = titles()
    grouped: dict[str, list[tuple[str, str, str]]] = {}
    for group, name, alias in catalogue_entries():
        grouped.setdefault(group, []).append((name, alias, known.get(name, "")))
    for group, name, title in OWN + chart_entries():
        grouped.setdefault(group, []).append((name, "", known.get(name, title)))

    states = {name: state_of(name, in_python) for group in grouped.values() for name, _, _ in group}
    done = sum(1 for s in states.values() if s == "done")
    core = sum(1 for s in states.values() if s == "core")
    total = len(states)

    lines = [
        f"<!-- {BANNER} -->",
        "",
        "# Progress",
        "",
        f"**{done} of {total} shipped**, {core} more written in the Rust core and waiting",
        f"for a Python binding, {total - done - core} not started.",
        "",
        "`[x]` shipped: `spec.yaml`, `mod.rs`, `doc.md` and golden data all present,",
        "and callable from Python. `[~]` written in the core but not yet bound.",
        "`[ ]` not started. A star marks the 0.1 release set",
        "(`docs/INDICATORS.md` section 2.1).",
        "",
        "Every mark is read off the repository by",
        "`python scripts/catalogue/progress.py --write`, so this file cannot claim",
        "something is done that is not. CI checks it is current.",
        "",
        "| Group | Shipped | Total |",
        "| --- | --- | --- |",
    ]
    for group, members in grouped.items():
        shipped = sum(1 for name, _, _ in members if states[name] == "done")
        lines.append(f"| {group} | {shipped} | {len(members)} |")
    lines.append("")

    for group, members in grouped.items():
        shipped = sum(1 for name, _, _ in members if states[name] == "done")
        lines += [f"## {group} ({shipped} of {len(members)})", ""]
        for name, alias, title in sorted(members):
            state = states[name]
            star = " *" if name in RELEASE_SET else ""
            label = f"`{name}`"
            if alias:
                label += f" (`{alias}`)"
            if title:
                label += f" -- {title}"
            lines.append(f"- {MARK[state]} {label}{star}{SUFFIX[state]}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    text = render()
    if args.check:
        current = PROGRESS.read_text(encoding="utf-8") if PROGRESS.exists() else None
        if current != text:
            print(f"{PROGRESS.relative_to(REPO_ROOT)} is out of date", file=sys.stderr)
            return 1
        print(f"{PROGRESS.relative_to(REPO_ROOT)} is up to date")
        return 0
    if args.write:
        PROGRESS.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {PROGRESS.relative_to(REPO_ROOT)}")
        return 0
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
