"""Derive the TA-Lib-equivalent catalogue by interrogating the oracle.

    python scripts/catalogue/talib_catalogue.py --write     # refresh the doc
    python scripts/catalogue/talib_catalogue.py --check     # fail if it drifted

Every fact here comes from running ta-lib-python, not from reading TA-Lib's
source: names, groups, parameter defaults and output names from
``talib.abstract``, and the accepted range of each integer parameter by
bisecting the real library until it answers TA_BAD_PARAM. That keeps the
catalogue reproducible from the pinned dev dependency alone, and it is the same
rule the golden files follow (``docs/TESTING.md`` section 2): behaviour is
defined by what the oracle does, not by what a document says it does.

What this does *not* take from TA-Lib is any algorithm. Implementations are
written from published formulas and checked against the oracle
(``docs/CONVENTIONS.md`` section 4).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CATALOGUE = REPO_ROOT / "docs" / "INDICATORS_TALIB.md"
ENUMS = REPO_ROOT / "crates" / "trendlib" / "src" / "indicators" / "_enums.yaml"

BANNER = "@generated by scripts/catalogue/talib_catalogue.py -- do not edit"

# TrendLib groups, in display order, mapped from TA-Lib's group names.
GROUPS = [
    ("overlap", "Overlap studies", "Overlap Studies"),
    ("momentum", "Momentum", "Momentum Indicators"),
    ("volatility", "Volatility", "Volatility Indicators"),
    ("volume", "Volume", "Volume Indicators"),
    ("price", "Price transforms", "Price Transform"),
    ("cycle", "Cycle", "Cycle Indicators"),
    ("statistic", "Statistics", "Statistic Functions"),
    ("math", "Math transforms", "Math Transform"),
    ("operator", "Math operators", "Math Operators"),
    ("patterns", "Candlestick patterns", "Pattern Recognition"),
]
GROUP_OF = {talib_group: key for key, _, talib_group in GROUPS}

# ta-lib-python labels the two operands of an arithmetic operator `high` and
# `low`, which is an artifact of its abstract API rather than a meaning: `add`
# adds any two series. These get honest names.
INPUT_OVERRIDES = {
    "ADD": ["source0", "source1"],
    "SUB": ["source0", "source1"],
    "MULT": ["source0", "source1"],
    "DIV": ["source0", "source1"],
}

# ta-lib-python input name -> TrendLib input name.
INPUTS = {
    "real": "source",
    "real0": "source0",
    "real1": "source1",
    "open": "open",
    "high": "high",
    "low": "low",
    "close": "close",
    "volume": "volume",
    "periods": "periods",
}

# ta-lib-python parameter name -> TrendLib parameter name. Anything not listed
# falls through to `snake_case`, which already produces the right answer for
# penetration, acceleration, maximum, sigma, offset and the rest.
PARAMS = {
    "timeperiod": "period",
    "timeperiod1": "period1",
    "timeperiod2": "period2",
    "timeperiod3": "period3",
    "fastperiod": "fast_period",
    "slowperiod": "slow_period",
    "signalperiod": "signal_period",
    "matype": "ma_type",
    "fastmatype": "fast_ma_type",
    "slowmatype": "slow_ma_type",
    "signalmatype": "signal_ma_type",
    "rocmatype": "roc_ma_type",
    "nbdev": "nbdev",
    "nbdevup": "nbdev_up",
    "nbdevdn": "nbdev_dn",
    "fastk_period": "fastk_period",
    "fastd_period": "fastd_period",
    "fastd_matype": "fastd_ma_type",
    "slowk_period": "slowk_period",
    "slowk_matype": "slowk_ma_type",
    "slowd_period": "slowd_period",
    "slowd_matype": "slowd_ma_type",
    "fastlimit": "fast_limit",
    "slowlimit": "slow_limit",
    "minperiod": "min_period",
    "maxperiod": "max_period",
    "startvalue": "start_value",
    "offsetonreverse": "offset_on_reverse",
    "accelerationinitlong": "acceleration_init_long",
    "accelerationlong": "acceleration_long",
    "accelerationmaxlong": "acceleration_max_long",
    "accelerationinitshort": "acceleration_init_short",
    "accelerationshort": "acceleration_short",
    "accelerationmaxshort": "acceleration_max_short",
    "volumedivisor": "volume_divisor",
    "stddevperiod": "stddev_period",
    "streakperiod": "streak_period",
    "rankperiod": "rank_period",
    "rocperiod": "roc_period",
    "cmoperiod": "cmo_period",
    "atrperiod": "atr_period",
    "wmaperiod": "wma_period",
    "stopperiod": "stop_period",
    "cycleperiod": "cycle_period",
    "limitmove": "limit_move",
    "leftbars": "left_bars",
    "rightbars": "right_bars",
    "firstperiod": "first_period",
    "secondperiod": "second_period",
    "vfactor": "v_factor",
}
for _n in (1, 2, 3, 4):
    PARAMS[f"roc{_n}period"] = f"roc{_n}_period"
    PARAMS[f"sma{_n}period"] = f"sma{_n}_period"
    PARAMS[f"ma{_n}period"] = f"ma{_n}_period"

# ta-lib-python output suffix -> TrendLib suffix, where the obvious conversion
# would read badly or clash.
# Functions TrendLib defines differently from TA-Lib. The catalogue flags them
# so nobody writes a spec.yaml straight off this table; docs/INDICATORS.md
# section 3 is what governs them.
REDEFINED = {
    "vwap": "session-anchored by default (deviation 3); `tl.VWAP` keeps TA-Lib's "
    "never-resetting form",
}

# Output names docs/INDICATORS.md already approved differently from the
# mechanical conversion. Keyed by TrendLib function name.
OUTPUT_OVERRIDES = {
    "supertrend": ["supertrend", "supertrend_direction"],
}

OUTPUT_SUFFIX = {
    "upperband": "upper",
    "middleband": "middle",
    "lowerband": "lower",
    "macdsignal": "signal",
    "macdhist": "hist",
    "kstsignal": "signal",
    "aroonup": "up",
    "aroondown": "down",
    "highstop": "high_stop",
    "lowstop": "low_stop",
    "bullpower": "bull_power",
    "bearpower": "bear_power",
    "swinghigh": "swing_high",
    "swinglow": "swing_low",
    "inphase": "in_phase",
    "minidx": "min_index",
    "maxidx": "max_index",
    "quadrature": "quadrature",
    "sine": "sine",
    "leadsine": "lead_sine",
    "fastk": "k",
    "fastd": "d",
    "slowk": "k",
    "slowd": "d",
    "haopen": "open",
    "hahigh": "high",
    "halow": "low",
    "haclose": "close",
}


def snake(name: str) -> str:
    name = re.sub(r"[^0-9a-zA-Z]+", "_", name)
    name = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    return re.sub(r"_+", "_", name).strip("_").lower()


def function_name(talib_name: str) -> str:
    lower = talib_name.lower()
    if lower.startswith("cdl"):
        return f"cdl_{lower[3:]}"
    return lower


def output_names(name: str, talib_outputs: list[str]) -> list[str]:
    if name in OUTPUT_OVERRIDES:
        approved = OUTPUT_OVERRIDES[name]
        if len(approved) != len(talib_outputs):
            raise SystemExit(
                f"{name}: override has {len(approved)} outputs, oracle has {len(talib_outputs)}"
            )
        return approved
    if len(talib_outputs) == 1:
        return [name]
    names = []
    for raw in talib_outputs:
        suffix = OUTPUT_SUFFIX.get(raw.lower(), snake(raw))
        # The line a function is named after keeps the plain name: MACD's three
        # outputs are macd, macd_signal and macd_hist, never macd_macd.
        names.append(name if suffix == name else f"{name}_{suffix}")
    return names


def parameter_name(raw: str) -> str:
    return PARAMS.get(raw.lower(), snake(raw))


def accepts(function, arrays, defaults, param, value) -> bool:
    params = dict(defaults)
    params[param] = value
    try:
        function(*arrays, **params)
    except Exception as exc:
        # Any other failure is not a range rejection, so it does not narrow it.
        text = str(exc)
        return "TA_BAD_PARAM" not in text and "Bad Parameter" not in text
    return True


def probe_range(function, arrays, defaults, param, default) -> tuple[int, int]:
    """Smallest and largest value the oracle accepts, found by bisection.

    The default is accepted by construction, so it bounds both searches;
    looking past it walks into the rejected region on the other side.
    """
    low, high = -5, default
    if accepts(function, arrays, defaults, param, low):
        minimum = low
    else:
        while low < high:
            middle = (low + high) // 2
            if accepts(function, arrays, defaults, param, middle):
                high = middle
            else:
                low = middle + 1
        minimum = low

    low, high = default, 1_000_000
    if accepts(function, arrays, defaults, param, high):
        maximum = high
    else:
        while low < high:
            middle = (low + high + 1) // 2
            if accepts(function, arrays, defaults, param, middle):
                low = middle
            else:
                high = middle - 1
        maximum = low
    return minimum, maximum


# How far out a float parameter is probed before it counts as unbounded, and
# how close to a round number a boundary has to sit to be reported as one.
FLOAT_LIMIT = 1.0e9
FLOAT_EPSILON = 1.0e-9


def snap(boundary: float, function, arrays, defaults, param, inside: int) -> float:
    """`boundary` as the round number the oracle actually turns over at.

    Bisection converges on a value a hair away from the boundary rather than on
    the boundary itself, so this looks for a round number that is accepted
    while a step further out is refused. `inside` is the direction of the
    accepted side: -1 for a maximum, +1 for a minimum.
    """
    for digits in range(0, 7):
        candidate = round(boundary, digits)
        outside = candidate - inside * FLOAT_EPSILON * max(abs(candidate), 1.0)
        if accepts(function, arrays, defaults, param, candidate) and not accepts(
            function, arrays, defaults, param, outside
        ):
            return candidate
    raise SystemExit(f"{param}: the oracle's boundary near {boundary} is not a round number")


def probe_float_range(function, arrays, defaults, param, default):
    """Bounds for a float parameter, or `None` where the oracle takes anything.

    Most float parameters are multipliers the oracle never checks, so a range
    is only reported when something is actually refused.
    """
    takes_anything = all(
        accepts(function, arrays, defaults, param, value) for value in (-FLOAT_LIMIT, FLOAT_LIMIT)
    )
    if takes_anything:
        return None

    # One side can be bounded and the other not: a candlestick penetration
    # cannot be negative but has no ceiling.
    bounds: list[float | None] = []
    for inside, outside in ((1, -FLOAT_LIMIT), (-1, FLOAT_LIMIT)):
        if accepts(function, arrays, defaults, param, outside):
            bounds.append(None)
            continue
        low, high = outside, float(default)
        for _ in range(200):
            middle = (low + high) / 2
            if middle in (low, high):
                break
            if accepts(function, arrays, defaults, param, middle):
                high = middle
            else:
                low = middle
        bounds.append(snap(high, function, arrays, defaults, param, inside))

    minimum, maximum = bounds
    if (minimum is not None and default < minimum) or (maximum is not None and default > maximum):
        raise SystemExit(f"{param}: default {default} is outside the probed range")
    return minimum, maximum


def sample_arrays():
    import numpy as np

    count = 120
    generator = np.random.default_rng(1)
    close = 100.0 * np.exp(np.cumsum(generator.normal(0.0, 0.01, count)))
    opens = np.roll(close, 1)
    opens[0] = close[0]
    return {
        "close": close,
        "open": opens,
        "high": close * 1.005,
        "low": close * 0.995,
        "volume": generator.integers(1000, 5000, count).astype(float),
        "periods": np.full(count, 10.0),
        "real": close,
        "real0": close,
        "real1": close * 1.005,
    }


def describe(talib_name: str, arrays) -> dict:
    import talib
    from talib import abstract

    info = abstract.Function(talib_name).info
    name = function_name(talib_name)

    inputs = INPUT_OVERRIDES.get(talib_name)
    if inputs is None:
        inputs = _input_names(info)

    function = getattr(talib, talib_name)
    sample = [arrays[raw] for raw in _raw_inputs(info)]
    defaults = dict(info["parameters"])

    params = []
    for raw, default in defaults.items():
        entry = {"talib": raw, "name": parameter_name(raw), "default": default}
        if raw.lower().endswith("matype"):
            entry["type"] = "enum:MaType"
            entry["default"] = ma_type_name(default)
        elif isinstance(default, int) and not isinstance(default, bool):
            entry["type"] = "int"
            entry["min"], entry["max"] = probe_range(function, sample, defaults, raw, default)
        else:
            entry["type"] = "float"
            bounds = probe_float_range(function, sample, defaults, raw, default)
            if bounds is not None:
                minimum, maximum = bounds
                if minimum is not None:
                    entry["min"] = minimum
                if maximum is not None:
                    entry["max"] = maximum
        params.append(entry)

    return {
        "name": name,
        "talib": talib_name,
        "title": info["display_name"],
        "group": GROUP_OF[info["group"]],
        "inputs": inputs,
        "params": params,
        "outputs": output_names(name, info["output_names"]),
        "talib_outputs": list(info["output_names"]),
        "integer_output": info["output_names"] == ["integer"],
        "flags": list(info["function_flags"] or []),
    }


def _input_names(info) -> list[str]:
    """TrendLib names for a function's inputs.

    ta-lib-python reports a lone generic series as `price: close` because close
    is what it defaults to, not because the function is about closing prices:
    `sma` averages whatever it is handed. A function with only that key gets
    `source`; one that also carries a `prices` list is genuinely reading bars,
    so there `price` really is the close.
    """
    keys = set(info["input_names"])
    generic = keys == {"price"}
    names = []
    for key, value in info["input_names"].items():
        if key == "price" and generic:
            names.append("source")
        else:
            for raw in value if isinstance(value, list) else [value]:
                names.append(INPUTS[raw])
    return names


def ma_type_name(value: int) -> str:
    """TA-Lib's integer for a moving average, as the name a spec uses.

    `_enums.yaml` owns the mapping in one direction; inverting it here keeps
    the catalogue from carrying a second copy that could disagree.
    """
    import yaml

    numbers = yaml.safe_load(ENUMS.read_text())["MaType"]["talib_int"]
    for name, number in numbers.items():
        if number == value:
            return name
    raise SystemExit(f"_enums.yaml has no MaType with TA-Lib's integer {value}")


def _raw_inputs(info) -> list[str]:
    raw = []
    for value in info["input_names"].values():
        raw.extend(value if isinstance(value, list) else [value])
    return raw


def render(entries: list[dict], versions: tuple[str, str]) -> str:
    by_group: dict[str, list[dict]] = {key: [] for key, _, _ in GROUPS}
    for entry in entries:
        by_group[entry["group"]].append(entry)

    lines = [
        f"<!-- {BANNER} -->",
        "",
        "# TA-Lib-equivalent catalogue",
        "",
        f"Every function ta-lib-python {versions[0]} exposes (TA-Lib C {versions[1]}),",
        "with the TrendLib name, inputs, parameters and outputs each one gets.",
        "`docs/INDICATORS.md` holds the naming rules this file applies and the",
        "definitions of the indicators TA-Lib does not have.",
        "",
        "Everything below was read out of the oracle, not out of TA-Lib's source:",
        "names, groups, defaults and output names come from `talib.abstract`, and",
        "each integer range was found by bisecting the real library until it",
        "answered `TA_BAD_PARAM`. Regenerate with",
        "`python scripts/catalogue/talib_catalogue.py --write`; CI checks it.",
        "",
        "Every function here can be verified by running ta-lib-python (oracle T).",
        "The indicators with no runnable oracle, and the ones TrendLib defines",
        "differently, are in `docs/INDICATORS.md` section 3; rows marked with a",
        "dagger are governed by that section, not by this table.",
        "",
        "A range is probed with every other parameter at its default, so where",
        "two parameters constrain each other (`mavp`) the printed range is the",
        "slice the oracle accepts in that configuration, not the declared one.",
        "",
        f"Total: **{len(entries)} functions**.",
        "",
        "| Group | Functions |",
        "| --- | --- |",
    ]
    for key, title, _ in GROUPS:
        lines.append(f"| [{title}](#{key}) | {len(by_group[key])} |")
    lines.append("")

    for key, title, _ in GROUPS:
        members = by_group[key]
        if not members:
            continue
        lines += [
            f"## {title}",
            "",
            f'<a id="{key}"></a>',
            "",
            "| Function | Alias | Inputs | Parameters (default, range) | Outputs |",
            "| --- | --- | --- | --- | --- |",
        ]
        notes = []
        for entry in sorted(members, key=lambda e: e["name"]):
            params = render_params(entry["params"])
            outputs = ", ".join(f"`{name}`" for name in entry["outputs"])
            if entry["integer_output"]:
                outputs += " (int32)"
            mark = " &dagger;" if entry["name"] in REDEFINED else ""
            if mark:
                notes.append(f"&dagger; `{entry['name']}`: {REDEFINED[entry['name']]}.")
            lines.append(
                f"| `{entry['name']}`{mark} | `{entry['talib']}` | "
                f"{', '.join(f'`{i}`' for i in entry['inputs'])} | {params} | {outputs} |"
            )
        lines.append("")
        if notes:
            lines += [*notes, ""]

    return "\n".join(lines).rstrip("\n") + "\n"


def float_range(param: dict) -> str:
    """How a float parameter's bounds are written, with `any` for a side the
    oracle does not check."""
    if "min" not in param and "max" not in param:
        return "any"
    low = param.get("min", "any")
    high = param.get("max", "any")
    return f"[{low}, {high}]"


def render_params(params: list[dict]) -> str:
    if not params:
        return "--"
    rendered = []
    for param in params:
        if param["type"] == "int":
            rendered.append(
                f"`{param['name']}` {param['default']} [{param['min']}, {param['max']}]"
            )
        elif param["type"] == "float":
            rendered.append(f"`{param['name']}` {param['default']} {float_range(param)}")
        else:
            rendered.append(f'`{param["name"]}` "{param["default"]}" (MaType)')
    return "; ".join(rendered)


def build() -> tuple[str, list[dict]]:
    import talib

    arrays = sample_arrays()
    entries = [describe(name, arrays) for name in sorted(talib.get_functions())]
    versions = (talib.__version__, talib.__ta_version__.decode().split()[0])
    return render(entries, versions), entries


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="refresh the catalogue")
    parser.add_argument("--check", action="store_true", help="fail if it is out of date")
    args = parser.parse_args()

    try:
        import talib  # noqa: F401
    except ImportError as exc:
        raise SystemExit(
            "ta-lib-python is missing; install the dev extra: pip install -e '.[dev]'"
        ) from exc

    text, entries = build()
    if args.check:
        current = CATALOGUE.read_text(encoding="utf-8") if CATALOGUE.exists() else None
        if current != text:
            print(f"{CATALOGUE.relative_to(REPO_ROOT)} is out of date", file=sys.stderr)
            return 1
        print(f"{CATALOGUE.relative_to(REPO_ROOT)} is up to date ({len(entries)} functions)")
        return 0

    if args.write:
        CATALOGUE.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {CATALOGUE.relative_to(REPO_ROOT)} ({len(entries)} functions)")
        return 0

    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
