// @generated by cargo xtask generate — do not edit

#![allow(dead_code)]

use super::{AnyStream, Columns, OpenAndFillResult, ParamSpec, Registered, TlError};
use trendlib::core::kernel::Kernel;

mod ad_adapter {
    use super::*;

    type Indicated = trendlib::indicators::ad::Ad;
    const INPUTS: usize = 4;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::ad::Params {
        let _ = values;
        trendlib::indicators::ad::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "ad takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::ad::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod atr_adapter {
    use super::*;

    type Indicated = trendlib::indicators::atr::Atr;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 14.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::atr::Params {
        trendlib::indicators::atr::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "atr takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::atr::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod cci_adapter {
    use super::*;

    type Indicated = trendlib::indicators::cci::Cci;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 14.0,
        min: 2.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::cci::Params {
        trendlib::indicators::cci::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "cci takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::cci::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod dema_adapter {
    use super::*;

    type Indicated = trendlib::indicators::dema::Dema;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 30.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::dema::Params {
        trendlib::indicators::dema::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "dema takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::dema::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod ema_adapter {
    use super::*;

    type Indicated = trendlib::indicators::ema::Ema;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 30.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::ema::Params {
        trendlib::indicators::ema::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "ema takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::ema::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod macd_adapter {
    use super::*;

    type Indicated = trendlib::indicators::macd::Macd;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 3;

    const PARAMS: &[ParamSpec] = &[
        ParamSpec {
            name: "fast_period",
            default: 12.0,
            min: 2.0,
            max: 100000.0,
            integral: true,
        },
        ParamSpec {
            name: "slow_period",
            default: 26.0,
            min: 2.0,
            max: 100000.0,
            integral: true,
        },
        ParamSpec {
            name: "signal_period",
            default: 9.0,
            min: 1.0,
            max: 100000.0,
            integral: true,
        },
    ];

    fn params(values: &[f64]) -> trendlib::indicators::macd::Params {
        trendlib::indicators::macd::Params {
            fast_period: values[0] as usize,
            slow_period: values[1] as usize,
            signal_period: values[2] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "macd takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::macd::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod natr_adapter {
    use super::*;

    type Indicated = trendlib::indicators::natr::Natr;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 14.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::natr::Params {
        trendlib::indicators::natr::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "natr takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::natr::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod obv_adapter {
    use super::*;

    type Indicated = trendlib::indicators::obv::Obv;
    const INPUTS: usize = 2;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::obv::Params {
        let _ = values;
        trendlib::indicators::obv::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "obv takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::obv::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod roc_adapter {
    use super::*;

    type Indicated = trendlib::indicators::roc::Roc;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 10.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::roc::Params {
        trendlib::indicators::roc::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "roc takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::roc::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod rsi_adapter {
    use super::*;

    type Indicated = trendlib::indicators::rsi::Rsi;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 14.0,
        min: 2.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::rsi::Params {
        trendlib::indicators::rsi::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "rsi takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::rsi::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod sma_adapter {
    use super::*;

    type Indicated = trendlib::indicators::sma::Sma;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 30.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::sma::Params {
        trendlib::indicators::sma::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "sma takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::sma::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod tema_adapter {
    use super::*;

    type Indicated = trendlib::indicators::tema::Tema;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 30.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::tema::Params {
        trendlib::indicators::tema::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "tema takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::tema::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod trange_adapter {
    use super::*;

    type Indicated = trendlib::indicators::trange::Trange;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::trange::Params {
        let _ = values;
        trendlib::indicators::trange::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "trange takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::trange::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod willr_adapter {
    use super::*;

    type Indicated = trendlib::indicators::willr::Willr;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 14.0,
        min: 2.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::willr::Params {
        trendlib::indicators::willr::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "willr takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::willr::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod wma_adapter {
    use super::*;

    type Indicated = trendlib::indicators::wma::Wma;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 30.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::wma::Params {
        trendlib::indicators::wma::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "wma takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::wma::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

pub fn registered() -> Vec<Registered> {
    vec![
        ad_adapter::registered(),
        atr_adapter::registered(),
        cci_adapter::registered(),
        dema_adapter::registered(),
        ema_adapter::registered(),
        macd_adapter::registered(),
        natr_adapter::registered(),
        obv_adapter::registered(),
        roc_adapter::registered(),
        rsi_adapter::registered(),
        sma_adapter::registered(),
        tema_adapter::registered(),
        trange_adapter::registered(),
        willr_adapter::registered(),
        wma_adapter::registered(),
    ]
}
