// @generated by cargo xtask generate — do not edit

#![allow(dead_code)]

use super::{AnyStream, Columns, OpenAndFillResult, ParamSpec, Registered, TlError};
use trendlib::core::kernel::Kernel;

mod acos_adapter {
    use super::*;

    type Indicated = trendlib::indicators::acos::Acos;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::acos::Params {
        let _ = values;
        trendlib::indicators::acos::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "acos takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::acos::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod ad_adapter {
    use super::*;

    type Indicated = trendlib::indicators::ad::Ad;
    const INPUTS: usize = 4;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::ad::Params {
        let _ = values;
        trendlib::indicators::ad::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "ad takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::ad::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: true,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod add_adapter {
    use super::*;

    type Indicated = trendlib::indicators::add::Add;
    const INPUTS: usize = 2;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::add::Params {
        let _ = values;
        trendlib::indicators::add::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "add takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::add::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod asin_adapter {
    use super::*;

    type Indicated = trendlib::indicators::asin::Asin;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::asin::Params {
        let _ = values;
        trendlib::indicators::asin::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "asin takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::asin::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod atan_adapter {
    use super::*;

    type Indicated = trendlib::indicators::atan::Atan;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::atan::Params {
        let _ = values;
        trendlib::indicators::atan::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "atan takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::atan::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod atr_adapter {
    use super::*;

    type Indicated = trendlib::indicators::atr::Atr;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 14.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::atr::Params {
        trendlib::indicators::atr::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "atr takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::atr::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod avgprice_adapter {
    use super::*;

    type Indicated = trendlib::indicators::avgprice::Avgprice;
    const INPUTS: usize = 4;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::avgprice::Params {
        let _ = values;
        trendlib::indicators::avgprice::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "avgprice takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::avgprice::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod cci_adapter {
    use super::*;

    type Indicated = trendlib::indicators::cci::Cci;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 14.0,
        min: 2.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::cci::Params {
        trendlib::indicators::cci::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "cci takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::cci::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod ceil_adapter {
    use super::*;

    type Indicated = trendlib::indicators::ceil::Ceil;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::ceil::Params {
        let _ = values;
        trendlib::indicators::ceil::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "ceil takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::ceil::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod cos_adapter {
    use super::*;

    type Indicated = trendlib::indicators::cos::Cos;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::cos::Params {
        let _ = values;
        trendlib::indicators::cos::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "cos takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::cos::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod cosh_adapter {
    use super::*;

    type Indicated = trendlib::indicators::cosh::Cosh;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::cosh::Params {
        let _ = values;
        trendlib::indicators::cosh::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "cosh takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::cosh::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod cumsum_adapter {
    use super::*;

    type Indicated = trendlib::indicators::cumsum::Cumsum;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::cumsum::Params {
        let _ = values;
        trendlib::indicators::cumsum::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "cumsum takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::cumsum::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: true,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod dema_adapter {
    use super::*;

    type Indicated = trendlib::indicators::dema::Dema;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 30.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::dema::Params {
        trendlib::indicators::dema::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "dema takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::dema::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod div_adapter {
    use super::*;

    type Indicated = trendlib::indicators::div::Div;
    const INPUTS: usize = 2;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::div::Params {
        let _ = values;
        trendlib::indicators::div::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "div takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::div::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod ema_adapter {
    use super::*;

    type Indicated = trendlib::indicators::ema::Ema;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 30.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::ema::Params {
        trendlib::indicators::ema::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "ema takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::ema::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod exp_adapter {
    use super::*;

    type Indicated = trendlib::indicators::exp::Exp;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::exp::Params {
        let _ = values;
        trendlib::indicators::exp::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "exp takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::exp::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod floor_adapter {
    use super::*;

    type Indicated = trendlib::indicators::floor::Floor;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::floor::Params {
        let _ = values;
        trendlib::indicators::floor::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "floor takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::floor::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod ln_adapter {
    use super::*;

    type Indicated = trendlib::indicators::ln::Ln;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::ln::Params {
        let _ = values;
        trendlib::indicators::ln::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "ln takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::ln::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod log10_adapter {
    use super::*;

    type Indicated = trendlib::indicators::log10::Log10;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::log10::Params {
        let _ = values;
        trendlib::indicators::log10::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "log10 takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::log10::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod macd_adapter {
    use super::*;

    type Indicated = trendlib::indicators::macd::Macd;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 3;

    const PARAMS: &[ParamSpec] = &[
        ParamSpec {
            name: "fast_period",
            default: 12.0,
            min: 2.0,
            max: 100000.0,
            integral: true,
        },
        ParamSpec {
            name: "slow_period",
            default: 26.0,
            min: 2.0,
            max: 100000.0,
            integral: true,
        },
        ParamSpec {
            name: "signal_period",
            default: 9.0,
            min: 1.0,
            max: 100000.0,
            integral: true,
        },
    ];

    fn params(values: &[f64]) -> trendlib::indicators::macd::Params {
        trendlib::indicators::macd::Params {
            fast_period: values[0] as usize,
            slow_period: values[1] as usize,
            signal_period: values[2] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "macd takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::macd::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod medprice_adapter {
    use super::*;

    type Indicated = trendlib::indicators::medprice::Medprice;
    const INPUTS: usize = 2;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::medprice::Params {
        let _ = values;
        trendlib::indicators::medprice::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "medprice takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::medprice::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod mult_adapter {
    use super::*;

    type Indicated = trendlib::indicators::mult::Mult;
    const INPUTS: usize = 2;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::mult::Params {
        let _ = values;
        trendlib::indicators::mult::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "mult takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::mult::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod natr_adapter {
    use super::*;

    type Indicated = trendlib::indicators::natr::Natr;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 14.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::natr::Params {
        trendlib::indicators::natr::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "natr takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::natr::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod obv_adapter {
    use super::*;

    type Indicated = trendlib::indicators::obv::Obv;
    const INPUTS: usize = 2;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::obv::Params {
        let _ = values;
        trendlib::indicators::obv::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "obv takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::obv::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: true,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod roc_adapter {
    use super::*;

    type Indicated = trendlib::indicators::roc::Roc;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 10.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::roc::Params {
        trendlib::indicators::roc::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "roc takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::roc::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod rsi_adapter {
    use super::*;

    type Indicated = trendlib::indicators::rsi::Rsi;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 14.0,
        min: 2.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::rsi::Params {
        trendlib::indicators::rsi::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "rsi takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::rsi::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod sin_adapter {
    use super::*;

    type Indicated = trendlib::indicators::sin::Sin;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::sin::Params {
        let _ = values;
        trendlib::indicators::sin::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "sin takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::sin::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod sinh_adapter {
    use super::*;

    type Indicated = trendlib::indicators::sinh::Sinh;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::sinh::Params {
        let _ = values;
        trendlib::indicators::sinh::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "sinh takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::sinh::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod sma_adapter {
    use super::*;

    type Indicated = trendlib::indicators::sma::Sma;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 30.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::sma::Params {
        trendlib::indicators::sma::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "sma takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::sma::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod sqrt_adapter {
    use super::*;

    type Indicated = trendlib::indicators::sqrt::Sqrt;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::sqrt::Params {
        let _ = values;
        trendlib::indicators::sqrt::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "sqrt takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::sqrt::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod sub_adapter {
    use super::*;

    type Indicated = trendlib::indicators::sub::Sub;
    const INPUTS: usize = 2;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::sub::Params {
        let _ = values;
        trendlib::indicators::sub::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "sub takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::sub::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod tan_adapter {
    use super::*;

    type Indicated = trendlib::indicators::tan::Tan;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::tan::Params {
        let _ = values;
        trendlib::indicators::tan::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "tan takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::tan::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod tanh_adapter {
    use super::*;

    type Indicated = trendlib::indicators::tanh::Tanh;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::tanh::Params {
        let _ = values;
        trendlib::indicators::tanh::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "tanh takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::tanh::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: true,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod tema_adapter {
    use super::*;

    type Indicated = trendlib::indicators::tema::Tema;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 30.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::tema::Params {
        trendlib::indicators::tema::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "tema takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::tema::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod trange_adapter {
    use super::*;

    type Indicated = trendlib::indicators::trange::Trange;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::trange::Params {
        let _ = values;
        trendlib::indicators::trange::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "trange takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::trange::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod typprice_adapter {
    use super::*;

    type Indicated = trendlib::indicators::typprice::Typprice;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::typprice::Params {
        let _ = values;
        trendlib::indicators::typprice::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "typprice takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::typprice::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod wclprice_adapter {
    use super::*;

    type Indicated = trendlib::indicators::wclprice::Wclprice;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[];

    fn params(values: &[f64]) -> trendlib::indicators::wclprice::Params {
        let _ = values;
        trendlib::indicators::wclprice::Params
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "wclprice takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::wclprice::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod willr_adapter {
    use super::*;

    type Indicated = trendlib::indicators::willr::Willr;
    const INPUTS: usize = 3;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 14.0,
        min: 2.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::willr::Params {
        trendlib::indicators::willr::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "willr takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::willr::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

mod wma_adapter {
    use super::*;

    type Indicated = trendlib::indicators::wma::Wma;
    const INPUTS: usize = 1;
    const OUTPUTS: usize = 1;

    const PARAMS: &[ParamSpec] = &[ParamSpec {
        name: "period",
        default: 30.0,
        min: 1.0,
        max: 100000.0,
        integral: true,
    }];

    fn params(values: &[f64]) -> trendlib::indicators::wma::Params {
        trendlib::indicators::wma::Params {
            period: values[0] as usize,
        }
    }

    fn columns<'a>(inputs: &[&'a [f64]]) -> [&'a [f64]; INPUTS] {
        assert_eq!(inputs.len(), INPUTS, "wma takes {INPUTS} inputs");
        std::array::from_fn(|i| inputs[i])
    }

    fn batch(inputs: &[&[f64]], values: &[f64]) -> Result<Columns, TlError> {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::batch(columns(inputs), &params(values))
            .map(|out| out.to_vec())
    }

    fn lookback(values: &[f64]) -> usize {
        <Indicated as Kernel<INPUTS, OUTPUTS>>::lookback(&params(values))
    }

    fn open_and_fill(inputs: &[&[f64]], values: &[f64]) -> OpenAndFillResult {
        let (stream, out) = <Indicated as Kernel<INPUTS, OUTPUTS>>::open_and_fill(
            columns(inputs),
            &params(values),
        )?;
        Ok((Box::new(stream) as Box<dyn AnyStream>, out.to_vec()))
    }

    pub fn registered() -> Registered {
        Registered {
            name: trendlib::indicators::wma::NAME,
            inputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::INPUTS,
            outputs: &<Indicated as Kernel<INPUTS, OUTPUTS>>::OUTPUTS,
            params: PARAMS,
            may_be_non_finite: false,
            path_dependent: false,
            batch,
            lookback,
            open_and_fill,
        }
    }
}

pub fn registered() -> Vec<Registered> {
    vec![
        acos_adapter::registered(),
        ad_adapter::registered(),
        add_adapter::registered(),
        asin_adapter::registered(),
        atan_adapter::registered(),
        atr_adapter::registered(),
        avgprice_adapter::registered(),
        cci_adapter::registered(),
        ceil_adapter::registered(),
        cos_adapter::registered(),
        cosh_adapter::registered(),
        cumsum_adapter::registered(),
        dema_adapter::registered(),
        div_adapter::registered(),
        ema_adapter::registered(),
        exp_adapter::registered(),
        floor_adapter::registered(),
        ln_adapter::registered(),
        log10_adapter::registered(),
        macd_adapter::registered(),
        medprice_adapter::registered(),
        mult_adapter::registered(),
        natr_adapter::registered(),
        obv_adapter::registered(),
        roc_adapter::registered(),
        rsi_adapter::registered(),
        sin_adapter::registered(),
        sinh_adapter::registered(),
        sma_adapter::registered(),
        sqrt_adapter::registered(),
        sub_adapter::registered(),
        tan_adapter::registered(),
        tanh_adapter::registered(),
        tema_adapter::registered(),
        trange_adapter::registered(),
        typprice_adapter::registered(),
        wclprice_adapter::registered(),
        willr_adapter::registered(),
        wma_adapter::registered(),
    ]
}
