# @generated by cargo xtask generate — do not edit
"""Batch functions and their TA-Lib aliases.

One wrapper per indicator, generated from its spec.yaml. Defaults come
from the extension module rather than being repeated here, so there is
one place they can be wrong.
"""

from __future__ import annotations

from typing import Any

from trendlib import _convert, _core

__all__ = [
    "AD",
    "ATR",
    "CCI",
    "DEMA",
    "EMA",
    "MACD",
    "NATR",
    "OBV",
    "ROC",
    "RSI",
    "SMA",
    "TEMA",
    "TRANGE",
    "WILLR",
    "WMA",
    "ad",
    "atr",
    "cci",
    "dema",
    "ema",
    "lookback",
    "macd",
    "natr",
    "obv",
    "roc",
    "rsi",
    "sma",
    "tema",
    "trange",
    "willr",
    "wma",
]

_PARAMS = _core.PARAMS


def ad(high=None, low=None, close=None, volume=None) -> Any:
    """Chaikin Accumulation Distribution Line.

    Returns
    -------
    ndarray or Series
        Running total of volume weighted by where each close sat in its own bar.
    """
    columns, carrier = _convert.bars(
        "ad",
        (high, low, close, volume),
        (
            "high",
            "low",
            "close",
            "volume",
        ),
        (
            "high",
            "low",
            "close",
            "volume",
        ),
    )
    out = _core.ad(*columns)
    return _convert.wrap_outputs(out, carrier, ("ad",))


def atr(
    high=None, low=None, close=None, *, period: int = _PARAMS["atr"]["period"]["default"]
) -> Any:
    """Average True Range.

    Parameters
    ----------
    period : int, default 14
        Number of bars the true ranges are averaged over, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Wilder average of the true range.
    """
    period = _convert.as_int("atr", "period", period)
    columns, carrier = _convert.bars(
        "atr",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.atr(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("atr",))


def cci(
    high=None, low=None, close=None, *, period: int = _PARAMS["cci"]["period"]["default"]
) -> Any:
    """Commodity Channel Index.

    Parameters
    ----------
    period : int, default 14
        Number of bars the average and the deviation are taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Distance of the typical price from its average, in units of its own mean deviation.
    """
    period = _convert.as_int("cci", "period", period)
    columns, carrier = _convert.bars(
        "cci",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.cci(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("cci",))


def dema(source=None, *, period: int = _PARAMS["dema"]["period"]["default"]) -> Any:
    """Double Exponential Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars each exponential stage is derived from, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Exponential average with most of its own lag subtracted back out.
    """
    period = _convert.as_int("dema", "period", period)
    columns, carrier = _convert.bars("dema", (source,), ("source",), ("series",))
    out = _core.dema(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("dema",))


def ema(source=None, *, period: int = _PARAMS["ema"]["period"]["default"]) -> Any:
    """Exponential Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars the smoothing factor is derived from, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Exponentially weighted mean of source.
    """
    period = _convert.as_int("ema", "period", period)
    columns, carrier = _convert.bars("ema", (source,), ("source",), ("series",))
    out = _core.ema(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("ema",))


def macd(
    source=None,
    *,
    fast_period: int = _PARAMS["macd"]["fast_period"]["default"],
    slow_period: int = _PARAMS["macd"]["slow_period"]["default"],
    signal_period: int = _PARAMS["macd"]["signal_period"]["default"],
) -> Any:
    """Moving Average Convergence Divergence.

    Parameters
    ----------
    fast_period : int, default 12
        Bars in the faster exponential average, from 2 to 100000.
    slow_period : int, default 26
        Bars in the slower exponential average, from 2 to 100000.
    signal_period : int, default 9
        Bars in the exponential average taken of the difference, from 1 to 100000.

    Returns
    -------
    tuple of ndarray, or DataFrame
        macd: Faster average minus the slower one.
        macd_signal: Exponential average of macd.
        macd_hist: macd minus its signal line.
    """
    fast_period = _convert.as_int("macd", "fast_period", fast_period)
    slow_period = _convert.as_int("macd", "slow_period", slow_period)
    signal_period = _convert.as_int("macd", "signal_period", signal_period)
    columns, carrier = _convert.bars("macd", (source,), ("source",), ("series",))
    out = _core.macd(
        *columns, fast_period=fast_period, slow_period=slow_period, signal_period=signal_period
    )
    return _convert.wrap_outputs(
        out,
        carrier,
        (
            "macd",
            "macd_signal",
            "macd_hist",
        ),
    )


def natr(
    high=None, low=None, close=None, *, period: int = _PARAMS["natr"]["period"]["default"]
) -> Any:
    """Normalized Average True Range.

    Parameters
    ----------
    period : int, default 14
        Number of bars the true ranges are averaged over, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Wilder average of the true range as a percentage of the close.
    """
    period = _convert.as_int("natr", "period", period)
    columns, carrier = _convert.bars(
        "natr",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.natr(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("natr",))


def obv(close=None, volume=None) -> Any:
    """On Balance Volume.

    Returns
    -------
    ndarray or Series
        Running total of volume, added on an up close and subtracted on a down close.
    """
    columns, carrier = _convert.bars(
        "obv",
        (close, volume),
        (
            "close",
            "volume",
        ),
        (
            "close",
            "volume",
        ),
    )
    out = _core.obv(*columns)
    return _convert.wrap_outputs(out, carrier, ("obv",))


def roc(source=None, *, period: int = _PARAMS["roc"]["period"]["default"]) -> Any:
    """Rate of Change.

    Parameters
    ----------
    period : int, default 10
        Number of bars back the comparison is made to, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Percentage change from the value period bars ago.
    """
    period = _convert.as_int("roc", "period", period)
    columns, carrier = _convert.bars("roc", (source,), ("source",), ("series",))
    out = _core.roc(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("roc",))


def rsi(source=None, *, period: int = _PARAMS["rsi"]["period"]["default"]) -> Any:
    """Relative Strength Index.

    Parameters
    ----------
    period : int, default 14
        Number of bar-to-bar changes the average gain and loss are taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Share of recent movement that was upward, from 0 to 100.
    """
    period = _convert.as_int("rsi", "period", period)
    columns, carrier = _convert.bars("rsi", (source,), ("source",), ("series",))
    out = _core.rsi(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("rsi",))


def sma(source=None, *, period: int = _PARAMS["sma"]["period"]["default"]) -> Any:
    """Simple Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars in the average, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Mean of the last period values of source.
    """
    period = _convert.as_int("sma", "period", period)
    columns, carrier = _convert.bars("sma", (source,), ("source",), ("series",))
    out = _core.sma(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("sma",))


def tema(source=None, *, period: int = _PARAMS["tema"]["period"]["default"]) -> Any:
    """Triple Exponential Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars each exponential stage is derived from, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Exponential average with lag removed through three stages.
    """
    period = _convert.as_int("tema", "period", period)
    columns, carrier = _convert.bars("tema", (source,), ("source",), ("series",))
    out = _core.tema(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("tema",))


def trange(high=None, low=None, close=None) -> Any:
    """True Range.

    Returns
    -------
    ndarray or Series
        Greater of the bar's own range and its distance from the previous close.
    """
    columns, carrier = _convert.bars(
        "trange",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.trange(*columns)
    return _convert.wrap_outputs(out, carrier, ("trange",))


def willr(
    high=None, low=None, close=None, *, period: int = _PARAMS["willr"]["period"]["default"]
) -> Any:
    """Williams Percent Range.

    Parameters
    ----------
    period : int, default 14
        Number of bars the high and low range is taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Where the close sits in the recent range, from -100 at the low to 0 at the high.
    """
    period = _convert.as_int("willr", "period", period)
    columns, carrier = _convert.bars(
        "willr",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.willr(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("willr",))


def wma(source=None, *, period: int = _PARAMS["wma"]["period"]["default"]) -> Any:
    """Weighted Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars in the average, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Mean of the last period values weighted by recency.
    """
    period = _convert.as_int("wma", "period", period)
    columns, carrier = _convert.bars("wma", (source,), ("source",), ("series",))
    out = _core.wma(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("wma",))


def lookback(name: str, **params: Any) -> int:
    """Warm-up rows before the first defined value."""
    known = _PARAMS.get(name)
    if known is None:
        raise _convert.InvalidInput(f"lookback: no indicator named {name!r}")
    unknown = set(params) - set(known)
    if unknown:
        raise TypeError(f"lookback: {name} has no parameter {sorted(unknown)[0]!r}")
    return _core.lookback(name, **params)


def AD(high, low, close, volume) -> Any:
    """TA-Lib-style alias for :func:`ad`."""
    return ad(high, low, close, volume)


def ATR(high, low, close, timeperiod: int = _PARAMS["atr"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`atr`."""
    return atr(high, low, close, period=timeperiod)


def CCI(high, low, close, timeperiod: int = _PARAMS["cci"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`cci`."""
    return cci(high, low, close, period=timeperiod)


def DEMA(source, timeperiod: int = _PARAMS["dema"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`dema`."""
    return dema(source, period=timeperiod)


def EMA(source, timeperiod: int = _PARAMS["ema"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`ema`."""
    return ema(source, period=timeperiod)


def MACD(
    source,
    fastperiod: int = _PARAMS["macd"]["fast_period"]["default"],
    slowperiod: int = _PARAMS["macd"]["slow_period"]["default"],
    signalperiod: int = _PARAMS["macd"]["signal_period"]["default"],
) -> Any:
    """TA-Lib-style alias for :func:`macd`."""
    return macd(source, fast_period=fastperiod, slow_period=slowperiod, signal_period=signalperiod)


def NATR(high, low, close, timeperiod: int = _PARAMS["natr"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`natr`."""
    return natr(high, low, close, period=timeperiod)


def OBV(close, volume) -> Any:
    """TA-Lib-style alias for :func:`obv`."""
    return obv(close, volume)


def ROC(source, timeperiod: int = _PARAMS["roc"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`roc`."""
    return roc(source, period=timeperiod)


def RSI(source, timeperiod: int = _PARAMS["rsi"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`rsi`."""
    return rsi(source, period=timeperiod)


def SMA(source, timeperiod: int = _PARAMS["sma"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`sma`."""
    return sma(source, period=timeperiod)


def TEMA(source, timeperiod: int = _PARAMS["tema"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`tema`."""
    return tema(source, period=timeperiod)


def TRANGE(high, low, close) -> Any:
    """TA-Lib-style alias for :func:`trange`."""
    return trange(high, low, close)


def WILLR(high, low, close, timeperiod: int = _PARAMS["willr"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`willr`."""
    return willr(high, low, close, period=timeperiod)


def WMA(source, timeperiod: int = _PARAMS["wma"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`wma`."""
    return wma(source, period=timeperiod)
