# @generated by cargo xtask generate — do not edit
"""Batch functions and their TA-Lib aliases.

One wrapper per indicator, generated from its spec.yaml. Defaults come
from the extension module rather than being repeated here, so there is
one place they can be wrong.
"""

from __future__ import annotations

from typing import Any

from trendlib import _convert, _core

__all__ = [
    "ACOS",
    "AD",
    "ADD",
    "ADX",
    "ADXR",
    "ASIN",
    "ATAN",
    "ATR",
    "AVGDEV",
    "AVGPRICE",
    "BOP",
    "CCI",
    "CEIL",
    "CMO",
    "COS",
    "COSH",
    "CUMSUM",
    "DEMA",
    "DIV",
    "DX",
    "EMA",
    "EXP",
    "FLOOR",
    "LN",
    "LOG10",
    "MACD",
    "MAX",
    "MEDPRICE",
    "MIDPOINT",
    "MIDPRICE",
    "MIN",
    "MINMAX",
    "MINUS_DI",
    "MINUS_DM",
    "MOM",
    "MULT",
    "NATR",
    "OBV",
    "PLUS_DI",
    "PLUS_DM",
    "RMA",
    "ROC",
    "ROCP",
    "ROCR",
    "ROCR100",
    "RSI",
    "SIN",
    "SINH",
    "SMA",
    "SQRT",
    "STDDEV",
    "SUB",
    "SUM",
    "TAN",
    "TANH",
    "TEMA",
    "TRANGE",
    "TRIMA",
    "TYPPRICE",
    "VAR",
    "WCLPRICE",
    "WILLR",
    "WMA",
    "acos",
    "ad",
    "add",
    "adx",
    "adxr",
    "asin",
    "atan",
    "atr",
    "avgdev",
    "avgprice",
    "bop",
    "cci",
    "ceil",
    "cmo",
    "cos",
    "cosh",
    "cumsum",
    "dema",
    "div",
    "dx",
    "ema",
    "exp",
    "floor",
    "ln",
    "log10",
    "lookback",
    "macd",
    "max",
    "medprice",
    "midpoint",
    "midprice",
    "min",
    "minmax",
    "minus_di",
    "minus_dm",
    "mom",
    "mult",
    "natr",
    "obv",
    "plus_di",
    "plus_dm",
    "rma",
    "roc",
    "rocp",
    "rocr",
    "rocr100",
    "rsi",
    "sin",
    "sinh",
    "sma",
    "sqrt",
    "stddev",
    "sub",
    "sum",
    "tan",
    "tanh",
    "tema",
    "trange",
    "trima",
    "typprice",
    "var",
    "wclprice",
    "willr",
    "wma",
]

_PARAMS = _core.PARAMS


def acos(source=None) -> Any:
    """Vector Arc Cosine.

    Returns
    -------
    ndarray or Series
        Arc Cosine of source, element by element.
    """
    columns, carrier = _convert.bars("acos", (source,), ("source",), ("series",))
    out = _core.acos(*columns)
    return _convert.wrap_outputs(out, carrier, ("acos",))


def ad(high=None, low=None, close=None, volume=None) -> Any:
    """Chaikin Accumulation Distribution Line.

    Returns
    -------
    ndarray or Series
        Running total of volume weighted by where each close sat in its own bar.
    """
    columns, carrier = _convert.bars(
        "ad",
        (high, low, close, volume),
        (
            "high",
            "low",
            "close",
            "volume",
        ),
        (
            "high",
            "low",
            "close",
            "volume",
        ),
    )
    out = _core.ad(*columns)
    return _convert.wrap_outputs(out, carrier, ("ad",))


def add(source0=None, source1=None) -> Any:
    """Vector Addition.

    Returns
    -------
    ndarray or Series
        Addition of the two inputs.
    """
    columns, carrier = _convert.bars(
        "add",
        (source0, source1),
        (
            "source0",
            "source1",
        ),
        (
            "series",
            "series",
        ),
    )
    out = _core.add(*columns)
    return _convert.wrap_outputs(out, carrier, ("add",))


def adx(
    high=None, low=None, close=None, *, period: int = _PARAMS["adx"]["period"]["default"]
) -> Any:
    """Average Directional Movement Index.

    Parameters
    ----------
    period : int, default 14
        Number of bars the movement is accumulated over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Wilder average of the directional movement index.
    """
    period = _convert.as_int("adx", "period", period)
    columns, carrier = _convert.bars(
        "adx",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.adx(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("adx",))


def adxr(
    high=None, low=None, close=None, *, period: int = _PARAMS["adxr"]["period"]["default"]
) -> Any:
    """Average Directional Movement Index Rating.

    Parameters
    ----------
    period : int, default 14
        Number of bars the movement is accumulated over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        The average index now and as it stood period minus one bars ago, averaged.
    """
    period = _convert.as_int("adxr", "period", period)
    columns, carrier = _convert.bars(
        "adxr",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.adxr(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("adxr",))


def asin(source=None) -> Any:
    """Vector Arc Sine.

    Returns
    -------
    ndarray or Series
        Arc Sine of source, element by element.
    """
    columns, carrier = _convert.bars("asin", (source,), ("source",), ("series",))
    out = _core.asin(*columns)
    return _convert.wrap_outputs(out, carrier, ("asin",))


def atan(source=None) -> Any:
    """Vector Arc Tangent.

    Returns
    -------
    ndarray or Series
        Arc Tangent of source, element by element.
    """
    columns, carrier = _convert.bars("atan", (source,), ("source",), ("series",))
    out = _core.atan(*columns)
    return _convert.wrap_outputs(out, carrier, ("atan",))


def atr(
    high=None, low=None, close=None, *, period: int = _PARAMS["atr"]["period"]["default"]
) -> Any:
    """Average True Range.

    Parameters
    ----------
    period : int, default 14
        Number of bars the true ranges are averaged over, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Wilder average of the true range.
    """
    period = _convert.as_int("atr", "period", period)
    columns, carrier = _convert.bars(
        "atr",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.atr(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("atr",))


def avgdev(source=None, *, period: int = _PARAMS["avgdev"]["period"]["default"]) -> Any:
    """Average Deviation.

    Parameters
    ----------
    period : int, default 14
        Number of bars the deviation is taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Mean distance of the last period values from their own average.
    """
    period = _convert.as_int("avgdev", "period", period)
    columns, carrier = _convert.bars("avgdev", (source,), ("source",), ("series",))
    out = _core.avgdev(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("avgdev",))


def avgprice(open=None, high=None, low=None, close=None) -> Any:
    """Average Price.

    Returns
    -------
    ndarray or Series
        The four prices a bar records, averaged equally.
    """
    columns, carrier = _convert.bars(
        "avgprice",
        (open, high, low, close),
        (
            "open",
            "high",
            "low",
            "close",
        ),
        (
            "open",
            "high",
            "low",
            "close",
        ),
    )
    out = _core.avgprice(*columns)
    return _convert.wrap_outputs(out, carrier, ("avgprice",))


def bop(open=None, high=None, low=None, close=None) -> Any:
    """Balance of Power.

    Returns
    -------
    ndarray or Series
        Where the close finished relative to the open, scaled by the bar's range.
    """
    columns, carrier = _convert.bars(
        "bop",
        (open, high, low, close),
        (
            "open",
            "high",
            "low",
            "close",
        ),
        (
            "open",
            "high",
            "low",
            "close",
        ),
    )
    out = _core.bop(*columns)
    return _convert.wrap_outputs(out, carrier, ("bop",))


def cci(
    high=None, low=None, close=None, *, period: int = _PARAMS["cci"]["period"]["default"]
) -> Any:
    """Commodity Channel Index.

    Parameters
    ----------
    period : int, default 14
        Number of bars the average and the deviation are taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Distance of the typical price from its average, in units of its own mean deviation.
    """
    period = _convert.as_int("cci", "period", period)
    columns, carrier = _convert.bars(
        "cci",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.cci(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("cci",))


def ceil(source=None) -> Any:
    """Vector Ceiling.

    Returns
    -------
    ndarray or Series
        Ceiling of source, element by element.
    """
    columns, carrier = _convert.bars("ceil", (source,), ("source",), ("series",))
    out = _core.ceil(*columns)
    return _convert.wrap_outputs(out, carrier, ("ceil",))


def cmo(source=None, *, period: int = _PARAMS["cmo"]["period"]["default"]) -> Any:
    """Chande Momentum Oscillator.

    Parameters
    ----------
    period : int, default 14
        Number of bar-to-bar changes the gains and losses are accumulated over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Gains minus losses as a share of the two combined, from -100 to 100.
    """
    period = _convert.as_int("cmo", "period", period)
    columns, carrier = _convert.bars("cmo", (source,), ("source",), ("series",))
    out = _core.cmo(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("cmo",))


def cos(source=None) -> Any:
    """Vector Cosine.

    Returns
    -------
    ndarray or Series
        Cosine of source, element by element.
    """
    columns, carrier = _convert.bars("cos", (source,), ("source",), ("series",))
    out = _core.cos(*columns)
    return _convert.wrap_outputs(out, carrier, ("cos",))


def cosh(source=None) -> Any:
    """Vector Hyperbolic Cosine.

    Returns
    -------
    ndarray or Series
        Hyperbolic Cosine of source, element by element.
    """
    columns, carrier = _convert.bars("cosh", (source,), ("source",), ("series",))
    out = _core.cosh(*columns)
    return _convert.wrap_outputs(out, carrier, ("cosh",))


def cumsum(source=None) -> Any:
    """Cumulative Sum.

    Returns
    -------
    ndarray or Series
        Running total of source from the first valid bar.
    """
    columns, carrier = _convert.bars("cumsum", (source,), ("source",), ("series",))
    out = _core.cumsum(*columns)
    return _convert.wrap_outputs(out, carrier, ("cumsum",))


def dema(source=None, *, period: int = _PARAMS["dema"]["period"]["default"]) -> Any:
    """Double Exponential Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars each exponential stage is derived from, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Exponential average with most of its own lag subtracted back out.
    """
    period = _convert.as_int("dema", "period", period)
    columns, carrier = _convert.bars("dema", (source,), ("source",), ("series",))
    out = _core.dema(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("dema",))


def div(source0=None, source1=None) -> Any:
    """Vector Division.

    Returns
    -------
    ndarray or Series
        Division of the two inputs.
    """
    columns, carrier = _convert.bars(
        "div",
        (source0, source1),
        (
            "source0",
            "source1",
        ),
        (
            "series",
            "series",
        ),
    )
    out = _core.div(*columns)
    return _convert.wrap_outputs(out, carrier, ("div",))


def dx(high=None, low=None, close=None, *, period: int = _PARAMS["dx"]["period"]["default"]) -> Any:
    """Directional Movement Index.

    Parameters
    ----------
    period : int, default 14
        Number of bars the movement is accumulated over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        How one-sided the directional movement has been, from 0 to 100.
    """
    period = _convert.as_int("dx", "period", period)
    columns, carrier = _convert.bars(
        "dx",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.dx(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("dx",))


def ema(source=None, *, period: int = _PARAMS["ema"]["period"]["default"]) -> Any:
    """Exponential Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars the smoothing factor is derived from, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Exponentially weighted mean of source.
    """
    period = _convert.as_int("ema", "period", period)
    columns, carrier = _convert.bars("ema", (source,), ("source",), ("series",))
    out = _core.ema(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("ema",))


def exp(source=None) -> Any:
    """Vector Exponential.

    Returns
    -------
    ndarray or Series
        Exponential of source, element by element.
    """
    columns, carrier = _convert.bars("exp", (source,), ("source",), ("series",))
    out = _core.exp(*columns)
    return _convert.wrap_outputs(out, carrier, ("exp",))


def floor(source=None) -> Any:
    """Vector Floor.

    Returns
    -------
    ndarray or Series
        Floor of source, element by element.
    """
    columns, carrier = _convert.bars("floor", (source,), ("source",), ("series",))
    out = _core.floor(*columns)
    return _convert.wrap_outputs(out, carrier, ("floor",))


def ln(source=None) -> Any:
    """Vector Natural Logarithm.

    Returns
    -------
    ndarray or Series
        Natural Logarithm of source, element by element.
    """
    columns, carrier = _convert.bars("ln", (source,), ("source",), ("series",))
    out = _core.ln(*columns)
    return _convert.wrap_outputs(out, carrier, ("ln",))


def log10(source=None) -> Any:
    """Vector Base 10 Logarithm.

    Returns
    -------
    ndarray or Series
        Base 10 Logarithm of source, element by element.
    """
    columns, carrier = _convert.bars("log10", (source,), ("source",), ("series",))
    out = _core.log10(*columns)
    return _convert.wrap_outputs(out, carrier, ("log10",))


def macd(
    source=None,
    *,
    fast_period: int = _PARAMS["macd"]["fast_period"]["default"],
    slow_period: int = _PARAMS["macd"]["slow_period"]["default"],
    signal_period: int = _PARAMS["macd"]["signal_period"]["default"],
) -> Any:
    """Moving Average Convergence Divergence.

    Parameters
    ----------
    fast_period : int, default 12
        Bars in the faster exponential average, from 2 to 100000.
    slow_period : int, default 26
        Bars in the slower exponential average, from 2 to 100000.
    signal_period : int, default 9
        Bars in the exponential average taken of the difference, from 1 to 100000.

    Returns
    -------
    tuple of ndarray, or DataFrame
        macd: Faster average minus the slower one.
        macd_signal: Exponential average of macd.
        macd_hist: macd minus its signal line.
    """
    fast_period = _convert.as_int("macd", "fast_period", fast_period)
    slow_period = _convert.as_int("macd", "slow_period", slow_period)
    signal_period = _convert.as_int("macd", "signal_period", signal_period)
    columns, carrier = _convert.bars("macd", (source,), ("source",), ("series",))
    out = _core.macd(
        *columns, fast_period=fast_period, slow_period=slow_period, signal_period=signal_period
    )
    return _convert.wrap_outputs(
        out,
        carrier,
        (
            "macd",
            "macd_signal",
            "macd_hist",
        ),
    )


def max(source=None, *, period: int = _PARAMS["max"]["period"]["default"]) -> Any:
    """Rolling Maximum.

    Parameters
    ----------
    period : int, default 30
        Number of bars the highest is taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        The highest value of the last period bars.
    """
    period = _convert.as_int("max", "period", period)
    columns, carrier = _convert.bars("max", (source,), ("source",), ("series",))
    out = _core.max(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("max",))


def medprice(high=None, low=None) -> Any:
    """Median Price.

    Returns
    -------
    ndarray or Series
        The midpoint of the bar's range.
    """
    columns, carrier = _convert.bars(
        "medprice",
        (high, low),
        (
            "high",
            "low",
        ),
        (
            "high",
            "low",
        ),
    )
    out = _core.medprice(*columns)
    return _convert.wrap_outputs(out, carrier, ("medprice",))


def midpoint(source=None, *, period: int = _PARAMS["midpoint"]["period"]["default"]) -> Any:
    """Midpoint over Period.

    Parameters
    ----------
    period : int, default 14
        Number of bars the range is taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Halfway between the highest and lowest value of the last period bars.
    """
    period = _convert.as_int("midpoint", "period", period)
    columns, carrier = _convert.bars("midpoint", (source,), ("source",), ("series",))
    out = _core.midpoint(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("midpoint",))


def midprice(high=None, low=None, *, period: int = _PARAMS["midprice"]["period"]["default"]) -> Any:
    """Midpoint Price over Period.

    Parameters
    ----------
    period : int, default 14
        Number of bars the range is taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Halfway between the highest high and the lowest low of the last period bars.
    """
    period = _convert.as_int("midprice", "period", period)
    columns, carrier = _convert.bars(
        "midprice",
        (high, low),
        (
            "high",
            "low",
        ),
        (
            "high",
            "low",
        ),
    )
    out = _core.midprice(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("midprice",))


def min(source=None, *, period: int = _PARAMS["min"]["period"]["default"]) -> Any:
    """Rolling Minimum.

    Parameters
    ----------
    period : int, default 30
        Number of bars the lowest is taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        The lowest value of the last period bars.
    """
    period = _convert.as_int("min", "period", period)
    columns, carrier = _convert.bars("min", (source,), ("source",), ("series",))
    out = _core.min(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("min",))


def minmax(source=None, *, period: int = _PARAMS["minmax"]["period"]["default"]) -> Any:
    """Rolling Minimum and Maximum.

    Parameters
    ----------
    period : int, default 30
        Number of bars the extremes are taken over, from 2 to 100000.

    Returns
    -------
    tuple of ndarray, or DataFrame
        minmax_min: The lowest value of the last period bars.
        minmax_max: The highest value of the last period bars.
    """
    period = _convert.as_int("minmax", "period", period)
    columns, carrier = _convert.bars("minmax", (source,), ("source",), ("series",))
    out = _core.minmax(*columns, period=period)
    return _convert.wrap_outputs(
        out,
        carrier,
        (
            "minmax_min",
            "minmax_max",
        ),
    )


def minus_di(
    high=None, low=None, close=None, *, period: int = _PARAMS["minus_di"]["period"]["default"]
) -> Any:
    """Minus Directional Indicator.

    Parameters
    ----------
    period : int, default 14
        Number of bars the movement is accumulated over, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Share of recent range that was covered downward, from 0 to 100.
    """
    period = _convert.as_int("minus_di", "period", period)
    columns, carrier = _convert.bars(
        "minus_di",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.minus_di(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("minus_di",))


def minus_dm(high=None, low=None, *, period: int = _PARAMS["minus_dm"]["period"]["default"]) -> Any:
    """Minus Directional Movement.

    Parameters
    ----------
    period : int, default 14
        Number of bars the movement is accumulated over, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Wilder's running total of downward directional movement.
    """
    period = _convert.as_int("minus_dm", "period", period)
    columns, carrier = _convert.bars(
        "minus_dm",
        (high, low),
        (
            "high",
            "low",
        ),
        (
            "high",
            "low",
        ),
    )
    out = _core.minus_dm(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("minus_dm",))


def mom(source=None, *, period: int = _PARAMS["mom"]["period"]["default"]) -> Any:
    """Momentum.

    Parameters
    ----------
    period : int, default 10
        Number of bars back the comparison is made to, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Momentum of source over period bars.
    """
    period = _convert.as_int("mom", "period", period)
    columns, carrier = _convert.bars("mom", (source,), ("source",), ("series",))
    out = _core.mom(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("mom",))


def mult(source0=None, source1=None) -> Any:
    """Vector Multiplication.

    Returns
    -------
    ndarray or Series
        Multiplication of the two inputs.
    """
    columns, carrier = _convert.bars(
        "mult",
        (source0, source1),
        (
            "source0",
            "source1",
        ),
        (
            "series",
            "series",
        ),
    )
    out = _core.mult(*columns)
    return _convert.wrap_outputs(out, carrier, ("mult",))


def natr(
    high=None, low=None, close=None, *, period: int = _PARAMS["natr"]["period"]["default"]
) -> Any:
    """Normalized Average True Range.

    Parameters
    ----------
    period : int, default 14
        Number of bars the true ranges are averaged over, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Wilder average of the true range as a percentage of the close.
    """
    period = _convert.as_int("natr", "period", period)
    columns, carrier = _convert.bars(
        "natr",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.natr(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("natr",))


def obv(close=None, volume=None) -> Any:
    """On Balance Volume.

    Returns
    -------
    ndarray or Series
        Running total of volume, added on an up close and subtracted on a down close.
    """
    columns, carrier = _convert.bars(
        "obv",
        (close, volume),
        (
            "close",
            "volume",
        ),
        (
            "close",
            "volume",
        ),
    )
    out = _core.obv(*columns)
    return _convert.wrap_outputs(out, carrier, ("obv",))


def plus_di(
    high=None, low=None, close=None, *, period: int = _PARAMS["plus_di"]["period"]["default"]
) -> Any:
    """Plus Directional Indicator.

    Parameters
    ----------
    period : int, default 14
        Number of bars the movement is accumulated over, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Share of recent range that was covered upward, from 0 to 100.
    """
    period = _convert.as_int("plus_di", "period", period)
    columns, carrier = _convert.bars(
        "plus_di",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.plus_di(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("plus_di",))


def plus_dm(high=None, low=None, *, period: int = _PARAMS["plus_dm"]["period"]["default"]) -> Any:
    """Plus Directional Movement.

    Parameters
    ----------
    period : int, default 14
        Number of bars the movement is accumulated over, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Wilder's running total of upward directional movement.
    """
    period = _convert.as_int("plus_dm", "period", period)
    columns, carrier = _convert.bars(
        "plus_dm",
        (high, low),
        (
            "high",
            "low",
        ),
        (
            "high",
            "low",
        ),
    )
    out = _core.plus_dm(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("plus_dm",))


def rma(source=None, *, period: int = _PARAMS["rma"]["period"]["default"]) -> Any:
    """Wilder Smoothed Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars the smoothing is derived from, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Wilder's smoothing of source.
    """
    period = _convert.as_int("rma", "period", period)
    columns, carrier = _convert.bars("rma", (source,), ("source",), ("series",))
    out = _core.rma(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("rma",))


def roc(source=None, *, period: int = _PARAMS["roc"]["period"]["default"]) -> Any:
    """Rate of Change.

    Parameters
    ----------
    period : int, default 10
        Number of bars back the comparison is made to, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Percentage change from the value period bars ago.
    """
    period = _convert.as_int("roc", "period", period)
    columns, carrier = _convert.bars("roc", (source,), ("source",), ("series",))
    out = _core.roc(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("roc",))


def rocp(source=None, *, period: int = _PARAMS["rocp"]["period"]["default"]) -> Any:
    """Rate of Change Percentage.

    Parameters
    ----------
    period : int, default 10
        Number of bars back the comparison is made to, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Rate of Change Percentage of source over period bars.
    """
    period = _convert.as_int("rocp", "period", period)
    columns, carrier = _convert.bars("rocp", (source,), ("source",), ("series",))
    out = _core.rocp(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("rocp",))


def rocr(source=None, *, period: int = _PARAMS["rocr"]["period"]["default"]) -> Any:
    """Rate of Change Ratio.

    Parameters
    ----------
    period : int, default 10
        Number of bars back the comparison is made to, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Rate of Change Ratio of source over period bars.
    """
    period = _convert.as_int("rocr", "period", period)
    columns, carrier = _convert.bars("rocr", (source,), ("source",), ("series",))
    out = _core.rocr(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("rocr",))


def rocr100(source=None, *, period: int = _PARAMS["rocr100"]["period"]["default"]) -> Any:
    """Rate of Change Ratio Times 100.

    Parameters
    ----------
    period : int, default 10
        Number of bars back the comparison is made to, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Rate of Change Ratio Times 100 of source over period bars.
    """
    period = _convert.as_int("rocr100", "period", period)
    columns, carrier = _convert.bars("rocr100", (source,), ("source",), ("series",))
    out = _core.rocr100(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("rocr100",))


def rsi(source=None, *, period: int = _PARAMS["rsi"]["period"]["default"]) -> Any:
    """Relative Strength Index.

    Parameters
    ----------
    period : int, default 14
        Number of bar-to-bar changes the average gain and loss are taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Share of recent movement that was upward, from 0 to 100.
    """
    period = _convert.as_int("rsi", "period", period)
    columns, carrier = _convert.bars("rsi", (source,), ("source",), ("series",))
    out = _core.rsi(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("rsi",))


def sin(source=None) -> Any:
    """Vector Sine.

    Returns
    -------
    ndarray or Series
        Sine of source, element by element.
    """
    columns, carrier = _convert.bars("sin", (source,), ("source",), ("series",))
    out = _core.sin(*columns)
    return _convert.wrap_outputs(out, carrier, ("sin",))


def sinh(source=None) -> Any:
    """Vector Hyperbolic Sine.

    Returns
    -------
    ndarray or Series
        Hyperbolic Sine of source, element by element.
    """
    columns, carrier = _convert.bars("sinh", (source,), ("source",), ("series",))
    out = _core.sinh(*columns)
    return _convert.wrap_outputs(out, carrier, ("sinh",))


def sma(source=None, *, period: int = _PARAMS["sma"]["period"]["default"]) -> Any:
    """Simple Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars in the average, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Mean of the last period values of source.
    """
    period = _convert.as_int("sma", "period", period)
    columns, carrier = _convert.bars("sma", (source,), ("source",), ("series",))
    out = _core.sma(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("sma",))


def sqrt(source=None) -> Any:
    """Vector Square Root.

    Returns
    -------
    ndarray or Series
        Square Root of source, element by element.
    """
    columns, carrier = _convert.bars("sqrt", (source,), ("source",), ("series",))
    out = _core.sqrt(*columns)
    return _convert.wrap_outputs(out, carrier, ("sqrt",))


def stddev(
    source=None,
    *,
    period: int = _PARAMS["stddev"]["period"]["default"],
    nbdev: float = _PARAMS["stddev"]["nbdev"]["default"],
) -> Any:
    """Standard Deviation.

    Parameters
    ----------
    period : int, default 5
        Number of bars the spread is taken over, from 2 to 100000.
    nbdev : float, default 1.0
        Multiplier applied to the deviation.

    Returns
    -------
    ndarray or Series
        Population standard deviation of the last period values, times nbdev.
    """
    period = _convert.as_int("stddev", "period", period)
    nbdev = _convert.as_float("stddev", "nbdev", nbdev)
    columns, carrier = _convert.bars("stddev", (source,), ("source",), ("series",))
    out = _core.stddev(*columns, period=period, nbdev=nbdev)
    return _convert.wrap_outputs(out, carrier, ("stddev",))


def sub(source0=None, source1=None) -> Any:
    """Vector Subtraction.

    Returns
    -------
    ndarray or Series
        Subtraction of the two inputs.
    """
    columns, carrier = _convert.bars(
        "sub",
        (source0, source1),
        (
            "source0",
            "source1",
        ),
        (
            "series",
            "series",
        ),
    )
    out = _core.sub(*columns)
    return _convert.wrap_outputs(out, carrier, ("sub",))


def sum(source=None, *, period: int = _PARAMS["sum"]["period"]["default"]) -> Any:
    """Summation.

    Parameters
    ----------
    period : int, default 30
        Number of bars added together, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Total of the last period values.
    """
    period = _convert.as_int("sum", "period", period)
    columns, carrier = _convert.bars("sum", (source,), ("source",), ("series",))
    out = _core.sum(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("sum",))


def tan(source=None) -> Any:
    """Vector Tangent.

    Returns
    -------
    ndarray or Series
        Tangent of source, element by element.
    """
    columns, carrier = _convert.bars("tan", (source,), ("source",), ("series",))
    out = _core.tan(*columns)
    return _convert.wrap_outputs(out, carrier, ("tan",))


def tanh(source=None) -> Any:
    """Vector Hyperbolic Tangent.

    Returns
    -------
    ndarray or Series
        Hyperbolic Tangent of source, element by element.
    """
    columns, carrier = _convert.bars("tanh", (source,), ("source",), ("series",))
    out = _core.tanh(*columns)
    return _convert.wrap_outputs(out, carrier, ("tanh",))


def tema(source=None, *, period: int = _PARAMS["tema"]["period"]["default"]) -> Any:
    """Triple Exponential Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars each exponential stage is derived from, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Exponential average with lag removed through three stages.
    """
    period = _convert.as_int("tema", "period", period)
    columns, carrier = _convert.bars("tema", (source,), ("source",), ("series",))
    out = _core.tema(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("tema",))


def trange(high=None, low=None, close=None) -> Any:
    """True Range.

    Returns
    -------
    ndarray or Series
        Greater of the bar's own range and its distance from the previous close.
    """
    columns, carrier = _convert.bars(
        "trange",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.trange(*columns)
    return _convert.wrap_outputs(out, carrier, ("trange",))


def trima(source=None, *, period: int = _PARAMS["trima"]["period"]["default"]) -> Any:
    """Triangular Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars in the average, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Mean of source weighted most heavily in the middle of the window.
    """
    period = _convert.as_int("trima", "period", period)
    columns, carrier = _convert.bars("trima", (source,), ("source",), ("series",))
    out = _core.trima(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("trima",))


def typprice(high=None, low=None, close=None) -> Any:
    """Typical Price.

    Returns
    -------
    ndarray or Series
        The average of the high, the low and the close.
    """
    columns, carrier = _convert.bars(
        "typprice",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.typprice(*columns)
    return _convert.wrap_outputs(out, carrier, ("typprice",))


def var(
    source=None,
    *,
    period: int = _PARAMS["var"]["period"]["default"],
    nbdev: float = _PARAMS["var"]["nbdev"]["default"],
) -> Any:
    """Variance.

    Parameters
    ----------
    period : int, default 5
        Number of bars the spread is taken over, from 1 to 100000.
    nbdev : float, default 1.0
        Accepted for TA-Lib compatibility and ignored, as TA-Lib ignores it.

    Returns
    -------
    ndarray or Series
        Population variance of the last period values.
    """
    period = _convert.as_int("var", "period", period)
    nbdev = _convert.as_float("var", "nbdev", nbdev)
    columns, carrier = _convert.bars("var", (source,), ("source",), ("series",))
    out = _core.var(*columns, period=period, nbdev=nbdev)
    return _convert.wrap_outputs(out, carrier, ("var",))


def wclprice(high=None, low=None, close=None) -> Any:
    """Weighted Close Price.

    Returns
    -------
    ndarray or Series
        The bar's range and its close, with the close counted twice.
    """
    columns, carrier = _convert.bars(
        "wclprice",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.wclprice(*columns)
    return _convert.wrap_outputs(out, carrier, ("wclprice",))


def willr(
    high=None, low=None, close=None, *, period: int = _PARAMS["willr"]["period"]["default"]
) -> Any:
    """Williams Percent Range.

    Parameters
    ----------
    period : int, default 14
        Number of bars the high and low range is taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Where the close sits in the recent range, from -100 at the low to 0 at the high.
    """
    period = _convert.as_int("willr", "period", period)
    columns, carrier = _convert.bars(
        "willr",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.willr(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("willr",))


def wma(source=None, *, period: int = _PARAMS["wma"]["period"]["default"]) -> Any:
    """Weighted Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars in the average, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Mean of the last period values weighted by recency.
    """
    period = _convert.as_int("wma", "period", period)
    columns, carrier = _convert.bars("wma", (source,), ("source",), ("series",))
    out = _core.wma(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("wma",))


def lookback(name: str, **params: Any) -> int:
    """Warm-up rows before the first defined value."""
    known = _PARAMS.get(name)
    if known is None:
        raise _convert.InvalidInput(f"lookback: no indicator named {name!r}")
    unknown = set(params) - set(known)
    if unknown:
        raise TypeError(f"lookback: {name} has no parameter {sorted(unknown)[0]!r}")
    return _core.lookback(name, **params)


def ACOS(source) -> Any:
    """TA-Lib-style alias for :func:`acos`."""
    return acos(source)


def AD(high, low, close, volume) -> Any:
    """TA-Lib-style alias for :func:`ad`."""
    return ad(high, low, close, volume)


def ADD(source0, source1) -> Any:
    """TA-Lib-style alias for :func:`add`."""
    return add(source0, source1)


def ADX(high, low, close, timeperiod: int = _PARAMS["adx"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`adx`."""
    return adx(high, low, close, period=timeperiod)


def ADXR(high, low, close, timeperiod: int = _PARAMS["adxr"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`adxr`."""
    return adxr(high, low, close, period=timeperiod)


def ASIN(source) -> Any:
    """TA-Lib-style alias for :func:`asin`."""
    return asin(source)


def ATAN(source) -> Any:
    """TA-Lib-style alias for :func:`atan`."""
    return atan(source)


def ATR(high, low, close, timeperiod: int = _PARAMS["atr"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`atr`."""
    return atr(high, low, close, period=timeperiod)


def AVGDEV(source, timeperiod: int = _PARAMS["avgdev"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`avgdev`."""
    return avgdev(source, period=timeperiod)


def AVGPRICE(open, high, low, close) -> Any:
    """TA-Lib-style alias for :func:`avgprice`."""
    return avgprice(open, high, low, close)


def BOP(open, high, low, close) -> Any:
    """TA-Lib-style alias for :func:`bop`."""
    return bop(open, high, low, close)


def CCI(high, low, close, timeperiod: int = _PARAMS["cci"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`cci`."""
    return cci(high, low, close, period=timeperiod)


def CEIL(source) -> Any:
    """TA-Lib-style alias for :func:`ceil`."""
    return ceil(source)


def CMO(source, timeperiod: int = _PARAMS["cmo"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`cmo`."""
    return cmo(source, period=timeperiod)


def COS(source) -> Any:
    """TA-Lib-style alias for :func:`cos`."""
    return cos(source)


def COSH(source) -> Any:
    """TA-Lib-style alias for :func:`cosh`."""
    return cosh(source)


def CUMSUM(source) -> Any:
    """TA-Lib-style alias for :func:`cumsum`."""
    return cumsum(source)


def DEMA(source, timeperiod: int = _PARAMS["dema"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`dema`."""
    return dema(source, period=timeperiod)


def DIV(source0, source1) -> Any:
    """TA-Lib-style alias for :func:`div`."""
    return div(source0, source1)


def DX(high, low, close, timeperiod: int = _PARAMS["dx"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`dx`."""
    return dx(high, low, close, period=timeperiod)


def EMA(source, timeperiod: int = _PARAMS["ema"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`ema`."""
    return ema(source, period=timeperiod)


def EXP(source) -> Any:
    """TA-Lib-style alias for :func:`exp`."""
    return exp(source)


def FLOOR(source) -> Any:
    """TA-Lib-style alias for :func:`floor`."""
    return floor(source)


def LN(source) -> Any:
    """TA-Lib-style alias for :func:`ln`."""
    return ln(source)


def LOG10(source) -> Any:
    """TA-Lib-style alias for :func:`log10`."""
    return log10(source)


def MACD(
    source,
    fastperiod: int = _PARAMS["macd"]["fast_period"]["default"],
    slowperiod: int = _PARAMS["macd"]["slow_period"]["default"],
    signalperiod: int = _PARAMS["macd"]["signal_period"]["default"],
) -> Any:
    """TA-Lib-style alias for :func:`macd`."""
    return macd(source, fast_period=fastperiod, slow_period=slowperiod, signal_period=signalperiod)


def MAX(source, timeperiod: int = _PARAMS["max"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`max`."""
    return max(source, period=timeperiod)


def MEDPRICE(high, low) -> Any:
    """TA-Lib-style alias for :func:`medprice`."""
    return medprice(high, low)


def MIDPOINT(source, timeperiod: int = _PARAMS["midpoint"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`midpoint`."""
    return midpoint(source, period=timeperiod)


def MIDPRICE(high, low, timeperiod: int = _PARAMS["midprice"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`midprice`."""
    return midprice(high, low, period=timeperiod)


def MIN(source, timeperiod: int = _PARAMS["min"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`min`."""
    return min(source, period=timeperiod)


def MINMAX(source, timeperiod: int = _PARAMS["minmax"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`minmax`."""
    return minmax(source, period=timeperiod)


def MINUS_DI(high, low, close, timeperiod: int = _PARAMS["minus_di"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`minus_di`."""
    return minus_di(high, low, close, period=timeperiod)


def MINUS_DM(high, low, timeperiod: int = _PARAMS["minus_dm"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`minus_dm`."""
    return minus_dm(high, low, period=timeperiod)


def MOM(source, timeperiod: int = _PARAMS["mom"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`mom`."""
    return mom(source, period=timeperiod)


def MULT(source0, source1) -> Any:
    """TA-Lib-style alias for :func:`mult`."""
    return mult(source0, source1)


def NATR(high, low, close, timeperiod: int = _PARAMS["natr"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`natr`."""
    return natr(high, low, close, period=timeperiod)


def OBV(close, volume) -> Any:
    """TA-Lib-style alias for :func:`obv`."""
    return obv(close, volume)


def PLUS_DI(high, low, close, timeperiod: int = _PARAMS["plus_di"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`plus_di`."""
    return plus_di(high, low, close, period=timeperiod)


def PLUS_DM(high, low, timeperiod: int = _PARAMS["plus_dm"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`plus_dm`."""
    return plus_dm(high, low, period=timeperiod)


def RMA(source, timeperiod: int = _PARAMS["rma"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`rma`."""
    return rma(source, period=timeperiod)


def ROC(source, timeperiod: int = _PARAMS["roc"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`roc`."""
    return roc(source, period=timeperiod)


def ROCP(source, timeperiod: int = _PARAMS["rocp"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`rocp`."""
    return rocp(source, period=timeperiod)


def ROCR(source, timeperiod: int = _PARAMS["rocr"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`rocr`."""
    return rocr(source, period=timeperiod)


def ROCR100(source, timeperiod: int = _PARAMS["rocr100"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`rocr100`."""
    return rocr100(source, period=timeperiod)


def RSI(source, timeperiod: int = _PARAMS["rsi"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`rsi`."""
    return rsi(source, period=timeperiod)


def SIN(source) -> Any:
    """TA-Lib-style alias for :func:`sin`."""
    return sin(source)


def SINH(source) -> Any:
    """TA-Lib-style alias for :func:`sinh`."""
    return sinh(source)


def SMA(source, timeperiod: int = _PARAMS["sma"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`sma`."""
    return sma(source, period=timeperiod)


def SQRT(source) -> Any:
    """TA-Lib-style alias for :func:`sqrt`."""
    return sqrt(source)


def STDDEV(
    source,
    timeperiod: int = _PARAMS["stddev"]["period"]["default"],
    nbdev: float = _PARAMS["stddev"]["nbdev"]["default"],
) -> Any:
    """TA-Lib-style alias for :func:`stddev`."""
    return stddev(source, period=timeperiod, nbdev=nbdev)


def SUB(source0, source1) -> Any:
    """TA-Lib-style alias for :func:`sub`."""
    return sub(source0, source1)


def SUM(source, timeperiod: int = _PARAMS["sum"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`sum`."""
    return sum(source, period=timeperiod)


def TAN(source) -> Any:
    """TA-Lib-style alias for :func:`tan`."""
    return tan(source)


def TANH(source) -> Any:
    """TA-Lib-style alias for :func:`tanh`."""
    return tanh(source)


def TEMA(source, timeperiod: int = _PARAMS["tema"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`tema`."""
    return tema(source, period=timeperiod)


def TRANGE(high, low, close) -> Any:
    """TA-Lib-style alias for :func:`trange`."""
    return trange(high, low, close)


def TRIMA(source, timeperiod: int = _PARAMS["trima"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`trima`."""
    return trima(source, period=timeperiod)


def TYPPRICE(high, low, close) -> Any:
    """TA-Lib-style alias for :func:`typprice`."""
    return typprice(high, low, close)


def VAR(
    source,
    timeperiod: int = _PARAMS["var"]["period"]["default"],
    nbdev: float = _PARAMS["var"]["nbdev"]["default"],
) -> Any:
    """TA-Lib-style alias for :func:`var`."""
    return var(source, period=timeperiod, nbdev=nbdev)


def WCLPRICE(high, low, close) -> Any:
    """TA-Lib-style alias for :func:`wclprice`."""
    return wclprice(high, low, close)


def WILLR(high, low, close, timeperiod: int = _PARAMS["willr"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`willr`."""
    return willr(high, low, close, period=timeperiod)


def WMA(source, timeperiod: int = _PARAMS["wma"]["period"]["default"]) -> Any:
    """TA-Lib-style alias for :func:`wma`."""
    return wma(source, period=timeperiod)
