# @generated by cargo xtask generate — do not edit
"""Batch functions and their TA-Lib aliases.

One wrapper per indicator, generated from its spec.yaml. Defaults come
from the extension module rather than being repeated here, so there is
one place they can be wrong.
"""

from __future__ import annotations

from typing import Any

from trendlib import _convert, _core

__all__ = [
    "ATR",
    "EMA",
    "NATR",
    "RSI",
    "SMA",
    "TRANGE",
    "WMA",
    "atr",
    "ema",
    "lookback",
    "natr",
    "rsi",
    "sma",
    "trange",
    "wma",
]

_PARAMS = _core.PARAMS


def atr(
    high=None, low=None, close=None, *, period: int = _PARAMS["atr"]["period"]["default"]
) -> Any:
    """Average True Range.

    Parameters
    ----------
    period : int, default 14
        Number of bars the true ranges are averaged over, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Wilder average of the true range.
    """
    period = _convert.as_int("atr", "period", period)
    columns, carrier = _convert.bars(
        "atr",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.atr(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("atr",))


def ema(source=None, *, period: int = _PARAMS["ema"]["period"]["default"]) -> Any:
    """Exponential Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars the smoothing factor is derived from, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Exponentially weighted mean of source.
    """
    period = _convert.as_int("ema", "period", period)
    columns, carrier = _convert.bars("ema", (source,), ("source",), ("series",))
    out = _core.ema(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("ema",))


def natr(
    high=None, low=None, close=None, *, period: int = _PARAMS["natr"]["period"]["default"]
) -> Any:
    """Normalized Average True Range.

    Parameters
    ----------
    period : int, default 14
        Number of bars the true ranges are averaged over, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Wilder average of the true range as a percentage of the close.
    """
    period = _convert.as_int("natr", "period", period)
    columns, carrier = _convert.bars(
        "natr",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.natr(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("natr",))


def rsi(source=None, *, period: int = _PARAMS["rsi"]["period"]["default"]) -> Any:
    """Relative Strength Index.

    Parameters
    ----------
    period : int, default 14
        Number of bar-to-bar changes the average gain and loss are taken over, from 2 to 100000.

    Returns
    -------
    ndarray or Series
        Share of recent movement that was upward, from 0 to 100.
    """
    period = _convert.as_int("rsi", "period", period)
    columns, carrier = _convert.bars("rsi", (source,), ("source",), ("series",))
    out = _core.rsi(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("rsi",))


def sma(source=None, *, period: int = _PARAMS["sma"]["period"]["default"]) -> Any:
    """Simple Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars in the average, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Mean of the last period values of source.
    """
    period = _convert.as_int("sma", "period", period)
    columns, carrier = _convert.bars("sma", (source,), ("source",), ("series",))
    out = _core.sma(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("sma",))


def trange(high=None, low=None, close=None) -> Any:
    """True Range.

    Returns
    -------
    ndarray or Series
        Greater of the bar's own range and its distance from the previous close.
    """
    columns, carrier = _convert.bars(
        "trange",
        (high, low, close),
        (
            "high",
            "low",
            "close",
        ),
        (
            "high",
            "low",
            "close",
        ),
    )
    out = _core.trange(*columns)
    return _convert.wrap_outputs(out, carrier, ("trange",))


def wma(source=None, *, period: int = _PARAMS["wma"]["period"]["default"]) -> Any:
    """Weighted Moving Average.

    Parameters
    ----------
    period : int, default 30
        Number of bars in the average, from 1 to 100000.

    Returns
    -------
    ndarray or Series
        Mean of the last period values weighted by recency.
    """
    period = _convert.as_int("wma", "period", period)
    columns, carrier = _convert.bars("wma", (source,), ("source",), ("series",))
    out = _core.wma(*columns, period=period)
    return _convert.wrap_outputs(out, carrier, ("wma",))


def lookback(name: str, **params: Any) -> int:
    """Warm-up rows before the first defined value."""
    known = _PARAMS.get(name)
    if known is None:
        raise _convert.InvalidInput(f"lookback: no indicator named {name!r}")
    unknown = set(params) - set(known)
    if unknown:
        raise TypeError(f"lookback: {name} has no parameter {sorted(unknown)[0]!r}")
    return _core.lookback(name, **params)


def ATR(high, low, close, timeperiod: int = _PARAMS["atr"]["period"]["default"]) -> Any:  # noqa: N802
    """TA-Lib-style alias for :func:`atr`."""
    return atr(high, low, close, period=timeperiod)


def EMA(source, timeperiod: int = _PARAMS["ema"]["period"]["default"]) -> Any:  # noqa: N802
    """TA-Lib-style alias for :func:`ema`."""
    return ema(source, period=timeperiod)


def NATR(high, low, close, timeperiod: int = _PARAMS["natr"]["period"]["default"]) -> Any:  # noqa: N802
    """TA-Lib-style alias for :func:`natr`."""
    return natr(high, low, close, period=timeperiod)


def RSI(source, timeperiod: int = _PARAMS["rsi"]["period"]["default"]) -> Any:  # noqa: N802
    """TA-Lib-style alias for :func:`rsi`."""
    return rsi(source, period=timeperiod)


def SMA(source, timeperiod: int = _PARAMS["sma"]["period"]["default"]) -> Any:  # noqa: N802
    """TA-Lib-style alias for :func:`sma`."""
    return sma(source, period=timeperiod)


def TRANGE(high, low, close) -> Any:  # noqa: N802
    """TA-Lib-style alias for :func:`trange`."""
    return trange(high, low, close)


def WMA(source, timeperiod: int = _PARAMS["wma"]["period"]["default"]) -> Any:  # noqa: N802
    """TA-Lib-style alias for :func:`wma`."""
    return wma(source, period=timeperiod)
