# @generated by cargo xtask generate — do not edit
"""Live indicator values, one factory per indicator.

A stream is a value, not a session: it holds no global state, `copy` is
an independent fork, and what it returns is bitwise identical to running
the batch function over the whole extended series.
"""

from __future__ import annotations

from typing import Any

from trendlib import _convert, _core
from trendlib._stream_base import Factory

__all__ = [
    "accbands",
    "acos",
    "ad",
    "add",
    "adx",
    "adxr",
    "apo",
    "aroon",
    "aroonosc",
    "asin",
    "atan",
    "atr",
    "avgdev",
    "avgprice",
    "bbands",
    "bop",
    "cci",
    "cdl_doji",
    "cdl_engulfing",
    "cdl_hammer",
    "ceil",
    "cmo",
    "cos",
    "cosh",
    "cumsum",
    "dema",
    "div",
    "donchian",
    "dpo",
    "dx",
    "ema",
    "exp",
    "floor",
    "ha",
    "hma",
    "kama",
    "kc",
    "linearreg",
    "linearreg_angle",
    "linearreg_intercept",
    "linearreg_slope",
    "ln",
    "log10",
    "ma",
    "macd",
    "macdext",
    "macdfix",
    "max",
    "maxindex",
    "medprice",
    "mfi",
    "midpoint",
    "midprice",
    "min",
    "minindex",
    "minmax",
    "minmaxindex",
    "minus_di",
    "minus_dm",
    "mom",
    "mult",
    "natr",
    "obv",
    "percentile",
    "percentrank",
    "plus_di",
    "plus_dm",
    "ppo",
    "rma",
    "roc",
    "rocp",
    "rocr",
    "rocr100",
    "rsi",
    "sin",
    "sinh",
    "sma",
    "sqrt",
    "stddev",
    "stoch",
    "stochf",
    "stochrsi",
    "sub",
    "sum",
    "t3",
    "tan",
    "tanh",
    "tema",
    "trange",
    "trima",
    "trix",
    "tsf",
    "typprice",
    "ultosc",
    "var",
    "vwma",
    "wclprice",
    "willr",
    "wma",
    "zlema",
]

accbands = Factory(
    "accbands",
    _core.AccbandsStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    (
        "accbands_upper",
        "accbands_middle",
        "accbands_lower",
    ),
)
acos = Factory("acos", _core.AcosStream, ("source",), ("series",), ("acos",))
ad = Factory(
    "ad",
    _core.AdStream,
    (
        "high",
        "low",
        "close",
        "volume",
    ),
    (
        "high",
        "low",
        "close",
        "volume",
    ),
    ("ad",),
)
add = Factory(
    "add",
    _core.AddStream,
    (
        "source0",
        "source1",
    ),
    (
        "series",
        "series",
    ),
    ("add",),
)
adx = Factory(
    "adx",
    _core.AdxStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("adx",),
)
adxr = Factory(
    "adxr",
    _core.AdxrStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("adxr",),
)
apo = Factory("apo", _core.ApoStream, ("source",), ("series",), ("apo",))
aroon = Factory(
    "aroon",
    _core.AroonStream,
    (
        "high",
        "low",
    ),
    (
        "high",
        "low",
    ),
    (
        "aroon_down",
        "aroon_up",
    ),
)
aroonosc = Factory(
    "aroonosc",
    _core.AroonoscStream,
    (
        "high",
        "low",
    ),
    (
        "high",
        "low",
    ),
    ("aroonosc",),
)
asin = Factory("asin", _core.AsinStream, ("source",), ("series",), ("asin",))
atan = Factory("atan", _core.AtanStream, ("source",), ("series",), ("atan",))
atr = Factory(
    "atr",
    _core.AtrStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("atr",),
)
avgdev = Factory("avgdev", _core.AvgdevStream, ("source",), ("series",), ("avgdev",))
avgprice = Factory(
    "avgprice",
    _core.AvgpriceStream,
    (
        "open",
        "high",
        "low",
        "close",
    ),
    (
        "open",
        "high",
        "low",
        "close",
    ),
    ("avgprice",),
)
bbands = Factory(
    "bbands",
    _core.BbandsStream,
    ("source",),
    ("series",),
    (
        "bbands_upper",
        "bbands_middle",
        "bbands_lower",
    ),
)
bop = Factory(
    "bop",
    _core.BopStream,
    (
        "open",
        "high",
        "low",
        "close",
    ),
    (
        "open",
        "high",
        "low",
        "close",
    ),
    ("bop",),
)
cci = Factory(
    "cci",
    _core.CciStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("cci",),
)
cdl_doji = Factory(
    "cdl_doji",
    _core.CdlDojiStream,
    (
        "open",
        "high",
        "low",
        "close",
    ),
    (
        "open",
        "high",
        "low",
        "close",
    ),
    ("cdl_doji",),
)
cdl_engulfing = Factory(
    "cdl_engulfing",
    _core.CdlEngulfingStream,
    (
        "open",
        "high",
        "low",
        "close",
    ),
    (
        "open",
        "high",
        "low",
        "close",
    ),
    ("cdl_engulfing",),
)
cdl_hammer = Factory(
    "cdl_hammer",
    _core.CdlHammerStream,
    (
        "open",
        "high",
        "low",
        "close",
    ),
    (
        "open",
        "high",
        "low",
        "close",
    ),
    ("cdl_hammer",),
)
ceil = Factory("ceil", _core.CeilStream, ("source",), ("series",), ("ceil",))
cmo = Factory("cmo", _core.CmoStream, ("source",), ("series",), ("cmo",))
cos = Factory("cos", _core.CosStream, ("source",), ("series",), ("cos",))
cosh = Factory("cosh", _core.CoshStream, ("source",), ("series",), ("cosh",))
cumsum = Factory("cumsum", _core.CumsumStream, ("source",), ("series",), ("cumsum",))
dema = Factory("dema", _core.DemaStream, ("source",), ("series",), ("dema",))
div = Factory(
    "div",
    _core.DivStream,
    (
        "source0",
        "source1",
    ),
    (
        "series",
        "series",
    ),
    ("div",),
)
donchian = Factory(
    "donchian",
    _core.DonchianStream,
    (
        "high",
        "low",
    ),
    (
        "high",
        "low",
    ),
    (
        "donchian_upper",
        "donchian_middle",
        "donchian_lower",
    ),
)
dpo = Factory("dpo", _core.DpoStream, ("source",), ("series",), ("dpo",))
dx = Factory(
    "dx",
    _core.DxStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("dx",),
)
ema = Factory("ema", _core.EmaStream, ("source",), ("series",), ("ema",))
exp = Factory("exp", _core.ExpStream, ("source",), ("series",), ("exp",))
floor = Factory("floor", _core.FloorStream, ("source",), ("series",), ("floor",))
ha = Factory(
    "ha",
    _core.HaStream,
    (
        "open",
        "high",
        "low",
        "close",
    ),
    (
        "open",
        "high",
        "low",
        "close",
    ),
    (
        "ha_open",
        "ha_high",
        "ha_low",
        "ha_close",
    ),
)
hma = Factory("hma", _core.HmaStream, ("source",), ("series",), ("hma",))
kama = Factory("kama", _core.KamaStream, ("source",), ("series",), ("kama",))
kc = Factory(
    "kc",
    _core.KcStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    (
        "kc_upper",
        "kc_middle",
        "kc_lower",
    ),
)
linearreg = Factory("linearreg", _core.LinearregStream, ("source",), ("series",), ("linearreg",))
linearreg_angle = Factory(
    "linearreg_angle", _core.LinearregAngleStream, ("source",), ("series",), ("linearreg_angle",)
)
linearreg_intercept = Factory(
    "linearreg_intercept",
    _core.LinearregInterceptStream,
    ("source",),
    ("series",),
    ("linearreg_intercept",),
)
linearreg_slope = Factory(
    "linearreg_slope", _core.LinearregSlopeStream, ("source",), ("series",), ("linearreg_slope",)
)
ln = Factory("ln", _core.LnStream, ("source",), ("series",), ("ln",))
log10 = Factory("log10", _core.Log10Stream, ("source",), ("series",), ("log10",))
ma = Factory("ma", _core.MaStream, ("source",), ("series",), ("ma",))
macd = Factory(
    "macd",
    _core.MacdStream,
    ("source",),
    ("series",),
    (
        "macd",
        "macd_signal",
        "macd_hist",
    ),
)
macdext = Factory(
    "macdext",
    _core.MacdextStream,
    ("source",),
    ("series",),
    (
        "macdext_macd",
        "macdext_signal",
        "macdext_hist",
    ),
)
macdfix = Factory(
    "macdfix",
    _core.MacdfixStream,
    ("source",),
    ("series",),
    (
        "macdfix_macd",
        "macdfix_signal",
        "macdfix_hist",
    ),
)
max = Factory("max", _core.MaxStream, ("source",), ("series",), ("max",))
maxindex = Factory("maxindex", _core.MaxindexStream, ("source",), ("series",), ("maxindex",))
medprice = Factory(
    "medprice",
    _core.MedpriceStream,
    (
        "high",
        "low",
    ),
    (
        "high",
        "low",
    ),
    ("medprice",),
)
mfi = Factory(
    "mfi",
    _core.MfiStream,
    (
        "high",
        "low",
        "close",
        "volume",
    ),
    (
        "high",
        "low",
        "close",
        "volume",
    ),
    ("mfi",),
)
midpoint = Factory("midpoint", _core.MidpointStream, ("source",), ("series",), ("midpoint",))
midprice = Factory(
    "midprice",
    _core.MidpriceStream,
    (
        "high",
        "low",
    ),
    (
        "high",
        "low",
    ),
    ("midprice",),
)
min = Factory("min", _core.MinStream, ("source",), ("series",), ("min",))
minindex = Factory("minindex", _core.MinindexStream, ("source",), ("series",), ("minindex",))
minmax = Factory(
    "minmax",
    _core.MinmaxStream,
    ("source",),
    ("series",),
    (
        "minmax_min",
        "minmax_max",
    ),
)
minmaxindex = Factory(
    "minmaxindex",
    _core.MinmaxindexStream,
    ("source",),
    ("series",),
    (
        "minmaxindex_min_index",
        "minmaxindex_max_index",
    ),
)
minus_di = Factory(
    "minus_di",
    _core.MinusDiStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("minus_di",),
)
minus_dm = Factory(
    "minus_dm",
    _core.MinusDmStream,
    (
        "high",
        "low",
    ),
    (
        "high",
        "low",
    ),
    ("minus_dm",),
)
mom = Factory("mom", _core.MomStream, ("source",), ("series",), ("mom",))
mult = Factory(
    "mult",
    _core.MultStream,
    (
        "source0",
        "source1",
    ),
    (
        "series",
        "series",
    ),
    ("mult",),
)
natr = Factory(
    "natr",
    _core.NatrStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("natr",),
)
obv = Factory(
    "obv",
    _core.ObvStream,
    (
        "close",
        "volume",
    ),
    (
        "close",
        "volume",
    ),
    ("obv",),
)
percentile = Factory(
    "percentile", _core.PercentileStream, ("source",), ("series",), ("percentile",)
)
percentrank = Factory(
    "percentrank", _core.PercentrankStream, ("source",), ("series",), ("percentrank",)
)
plus_di = Factory(
    "plus_di",
    _core.PlusDiStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("plus_di",),
)
plus_dm = Factory(
    "plus_dm",
    _core.PlusDmStream,
    (
        "high",
        "low",
    ),
    (
        "high",
        "low",
    ),
    ("plus_dm",),
)
ppo = Factory("ppo", _core.PpoStream, ("source",), ("series",), ("ppo",))
rma = Factory("rma", _core.RmaStream, ("source",), ("series",), ("rma",))
roc = Factory("roc", _core.RocStream, ("source",), ("series",), ("roc",))
rocp = Factory("rocp", _core.RocpStream, ("source",), ("series",), ("rocp",))
rocr = Factory("rocr", _core.RocrStream, ("source",), ("series",), ("rocr",))
rocr100 = Factory("rocr100", _core.Rocr100Stream, ("source",), ("series",), ("rocr100",))
rsi = Factory("rsi", _core.RsiStream, ("source",), ("series",), ("rsi",))
sin = Factory("sin", _core.SinStream, ("source",), ("series",), ("sin",))
sinh = Factory("sinh", _core.SinhStream, ("source",), ("series",), ("sinh",))
sma = Factory("sma", _core.SmaStream, ("source",), ("series",), ("sma",))
sqrt = Factory("sqrt", _core.SqrtStream, ("source",), ("series",), ("sqrt",))
stddev = Factory("stddev", _core.StddevStream, ("source",), ("series",), ("stddev",))
stoch = Factory(
    "stoch",
    _core.StochStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    (
        "stoch_k",
        "stoch_d",
    ),
)
stochf = Factory(
    "stochf",
    _core.StochfStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    (
        "stochf_k",
        "stochf_d",
    ),
)
stochrsi = Factory(
    "stochrsi",
    _core.StochrsiStream,
    ("source",),
    ("series",),
    (
        "stochrsi_k",
        "stochrsi_d",
    ),
)
sub = Factory(
    "sub",
    _core.SubStream,
    (
        "source0",
        "source1",
    ),
    (
        "series",
        "series",
    ),
    ("sub",),
)
sum = Factory("sum", _core.SumStream, ("source",), ("series",), ("sum",))
t3 = Factory("t3", _core.T3Stream, ("source",), ("series",), ("t3",))
tan = Factory("tan", _core.TanStream, ("source",), ("series",), ("tan",))
tanh = Factory("tanh", _core.TanhStream, ("source",), ("series",), ("tanh",))
tema = Factory("tema", _core.TemaStream, ("source",), ("series",), ("tema",))
trange = Factory(
    "trange",
    _core.TrangeStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("trange",),
)
trima = Factory("trima", _core.TrimaStream, ("source",), ("series",), ("trima",))
trix = Factory("trix", _core.TrixStream, ("source",), ("series",), ("trix",))
tsf = Factory("tsf", _core.TsfStream, ("source",), ("series",), ("tsf",))
typprice = Factory(
    "typprice",
    _core.TyppriceStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("typprice",),
)
ultosc = Factory(
    "ultosc",
    _core.UltoscStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("ultosc",),
)
var = Factory("var", _core.VarStream, ("source",), ("series",), ("var",))
vwma = Factory(
    "vwma",
    _core.VwmaStream,
    (
        "close",
        "volume",
    ),
    (
        "close",
        "volume",
    ),
    ("vwma",),
)
wclprice = Factory(
    "wclprice",
    _core.WclpriceStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("wclprice",),
)
willr = Factory(
    "willr",
    _core.WillrStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("willr",),
)
wma = Factory("wma", _core.WmaStream, ("source",), ("series",), ("wma",))
zlema = Factory("zlema", _core.ZlemaStream, ("source",), ("series",), ("zlema",))

_ = (Any, _convert)
