# @generated by cargo xtask generate — do not edit
"""Live indicator values, one factory per indicator.

A stream is a value, not a session: it holds no global state, `copy` is
an independent fork, and what it returns is bitwise identical to running
the batch function over the whole extended series.
"""

from __future__ import annotations

from typing import Any

from trendlib import _convert, _core
from trendlib._stream_base import Factory

__all__ = [
    "acos",
    "ad",
    "add",
    "asin",
    "atan",
    "atr",
    "avgdev",
    "avgprice",
    "cci",
    "ceil",
    "cos",
    "cosh",
    "cumsum",
    "dema",
    "div",
    "ema",
    "exp",
    "floor",
    "ln",
    "log10",
    "macd",
    "max",
    "medprice",
    "midpoint",
    "midprice",
    "min",
    "minmax",
    "mom",
    "mult",
    "natr",
    "obv",
    "roc",
    "rocp",
    "rocr",
    "rocr100",
    "rsi",
    "sin",
    "sinh",
    "sma",
    "sqrt",
    "stddev",
    "sub",
    "sum",
    "tan",
    "tanh",
    "tema",
    "trange",
    "typprice",
    "var",
    "wclprice",
    "willr",
    "wma",
]

acos = Factory("acos", _core.AcosStream, ("source",), ("series",), ("acos",))
ad = Factory(
    "ad",
    _core.AdStream,
    (
        "high",
        "low",
        "close",
        "volume",
    ),
    (
        "high",
        "low",
        "close",
        "volume",
    ),
    ("ad",),
)
add = Factory(
    "add",
    _core.AddStream,
    (
        "source0",
        "source1",
    ),
    (
        "series",
        "series",
    ),
    ("add",),
)
asin = Factory("asin", _core.AsinStream, ("source",), ("series",), ("asin",))
atan = Factory("atan", _core.AtanStream, ("source",), ("series",), ("atan",))
atr = Factory(
    "atr",
    _core.AtrStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("atr",),
)
avgdev = Factory("avgdev", _core.AvgdevStream, ("source",), ("series",), ("avgdev",))
avgprice = Factory(
    "avgprice",
    _core.AvgpriceStream,
    (
        "open",
        "high",
        "low",
        "close",
    ),
    (
        "open",
        "high",
        "low",
        "close",
    ),
    ("avgprice",),
)
cci = Factory(
    "cci",
    _core.CciStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("cci",),
)
ceil = Factory("ceil", _core.CeilStream, ("source",), ("series",), ("ceil",))
cos = Factory("cos", _core.CosStream, ("source",), ("series",), ("cos",))
cosh = Factory("cosh", _core.CoshStream, ("source",), ("series",), ("cosh",))
cumsum = Factory("cumsum", _core.CumsumStream, ("source",), ("series",), ("cumsum",))
dema = Factory("dema", _core.DemaStream, ("source",), ("series",), ("dema",))
div = Factory(
    "div",
    _core.DivStream,
    (
        "source0",
        "source1",
    ),
    (
        "series",
        "series",
    ),
    ("div",),
)
ema = Factory("ema", _core.EmaStream, ("source",), ("series",), ("ema",))
exp = Factory("exp", _core.ExpStream, ("source",), ("series",), ("exp",))
floor = Factory("floor", _core.FloorStream, ("source",), ("series",), ("floor",))
ln = Factory("ln", _core.LnStream, ("source",), ("series",), ("ln",))
log10 = Factory("log10", _core.Log10Stream, ("source",), ("series",), ("log10",))
macd = Factory(
    "macd",
    _core.MacdStream,
    ("source",),
    ("series",),
    (
        "macd",
        "macd_signal",
        "macd_hist",
    ),
)
max = Factory("max", _core.MaxStream, ("source",), ("series",), ("max",))
medprice = Factory(
    "medprice",
    _core.MedpriceStream,
    (
        "high",
        "low",
    ),
    (
        "high",
        "low",
    ),
    ("medprice",),
)
midpoint = Factory("midpoint", _core.MidpointStream, ("source",), ("series",), ("midpoint",))
midprice = Factory(
    "midprice",
    _core.MidpriceStream,
    (
        "high",
        "low",
    ),
    (
        "high",
        "low",
    ),
    ("midprice",),
)
min = Factory("min", _core.MinStream, ("source",), ("series",), ("min",))
minmax = Factory(
    "minmax",
    _core.MinmaxStream,
    ("source",),
    ("series",),
    (
        "minmax_min",
        "minmax_max",
    ),
)
mom = Factory("mom", _core.MomStream, ("source",), ("series",), ("mom",))
mult = Factory(
    "mult",
    _core.MultStream,
    (
        "source0",
        "source1",
    ),
    (
        "series",
        "series",
    ),
    ("mult",),
)
natr = Factory(
    "natr",
    _core.NatrStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("natr",),
)
obv = Factory(
    "obv",
    _core.ObvStream,
    (
        "close",
        "volume",
    ),
    (
        "close",
        "volume",
    ),
    ("obv",),
)
roc = Factory("roc", _core.RocStream, ("source",), ("series",), ("roc",))
rocp = Factory("rocp", _core.RocpStream, ("source",), ("series",), ("rocp",))
rocr = Factory("rocr", _core.RocrStream, ("source",), ("series",), ("rocr",))
rocr100 = Factory("rocr100", _core.Rocr100Stream, ("source",), ("series",), ("rocr100",))
rsi = Factory("rsi", _core.RsiStream, ("source",), ("series",), ("rsi",))
sin = Factory("sin", _core.SinStream, ("source",), ("series",), ("sin",))
sinh = Factory("sinh", _core.SinhStream, ("source",), ("series",), ("sinh",))
sma = Factory("sma", _core.SmaStream, ("source",), ("series",), ("sma",))
sqrt = Factory("sqrt", _core.SqrtStream, ("source",), ("series",), ("sqrt",))
stddev = Factory("stddev", _core.StddevStream, ("source",), ("series",), ("stddev",))
sub = Factory(
    "sub",
    _core.SubStream,
    (
        "source0",
        "source1",
    ),
    (
        "series",
        "series",
    ),
    ("sub",),
)
sum = Factory("sum", _core.SumStream, ("source",), ("series",), ("sum",))
tan = Factory("tan", _core.TanStream, ("source",), ("series",), ("tan",))
tanh = Factory("tanh", _core.TanhStream, ("source",), ("series",), ("tanh",))
tema = Factory("tema", _core.TemaStream, ("source",), ("series",), ("tema",))
trange = Factory(
    "trange",
    _core.TrangeStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("trange",),
)
typprice = Factory(
    "typprice",
    _core.TyppriceStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("typprice",),
)
var = Factory("var", _core.VarStream, ("source",), ("series",), ("var",))
wclprice = Factory(
    "wclprice",
    _core.WclpriceStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("wclprice",),
)
willr = Factory(
    "willr",
    _core.WillrStream,
    (
        "high",
        "low",
        "close",
    ),
    (
        "high",
        "low",
        "close",
    ),
    ("willr",),
)
wma = Factory("wma", _core.WmaStream, ("source",), ("series",), ("wma",))

_ = (Any, _convert)
